# Task runner: `just` lists recipes. CI runs these same recipes (.agents/knowledge/github/checks.md).

set shell := ["bash", "-euo", "pipefail", "-c"]

# Recipe arguments reach commands as "$1", "$@" — never pasted into the command text, where the
# shell would re-parse quotes and $(...) in them.
set positional-arguments

# List recipes
default:
    @just --list

# Everything CI checks without containers: hooks, scripts, metadata and versions, specs, READMEs
check: lint scripts-check validate spec-check docs-check

# Run every pre-commit hook on all files
lint:
    pre-commit run --all-files --show-diff-on-failure

# Type-check, lint, and unit-test the Deno scripts
scripts-check:
    deno check scripts/ .agents/skills/github-project-workflow/scripts/
    deno lint scripts/ .agents/skills/github-project-workflow/scripts/
    deno test --allow-read --allow-write=/tmp scripts/

# Validate feature layout, metadata, and version bumps against a base ref
validate base="origin/main":
    ./scripts/validate.ts --base "$1"

# Validate every OpenSpec spec and change in strict mode
spec-check:
    OPENSPEC_NO_UPDATE_CHECK=1 openspec validate --all --strict --no-interactive

# List unarchived OpenSpec changes; --ready shows the verdict CI gives a ready PR
spec-status *args:
    ./scripts/check_spec_archived.ts "$@"

# Print the CI test plan for the current branch
affected base="origin/main":
    ./scripts/affected.ts --base "$1"

# Autogenerated + duplicate tests on the feature's compatibility images (--image, --preserve, --keep)
test feature *args:
    ./scripts/test_feature.ts --feature "$1" "${@:2}"

# Run a feature's scenario tests
test-scenarios feature *args:
    ./scripts/test_feature.ts --feature "$1" --mode scenarios "${@:2}"

# Run the cross-feature scenarios in test/_global
test-global *args:
    ./scripts/test_feature.ts --mode global "$@"

# Regenerate every feature's README.md
docs:
    ./scripts/docs.ts

# Fail when a generated README.md is out of date
docs-check:
    ./scripts/docs.ts --check

# Scaffold src/<id> and test/<id> for a new feature (after its OpenSpec change exists)
new-feature id *args:
    ./scripts/new_feature.ts "$1" "${@:2}"

# Check a pull request title against the commit convention
check-title title:
    ./scripts/check_title.ts "$1"
