# Task runner: `just` lists recipes. CI runs these same recipes (.agents/knowledge/github/checks.md).

set shell := ["bash", "-euo", "pipefail", "-c"]

# Recipe arguments reach commands as "$1", "$@" — never pasted into the command text, where the
# shell would re-parse quotes and $(...) in them.
set positional-arguments

# List recipes
default:
    @just --list

# Everything CI checks without containers: formatting, shell scripts, Deno scripts, metadata, versions, specs, READMEs
check: lint scripts-check validate spec-check docs-check

# Check formatting (deno fmt) and shell scripts (shellcheck); the pre-commit hooks run on each commit
lint:
    deno fmt --check
    git ls-files -z '*.sh' | xargs -0 --no-run-if-empty shellcheck

# --allow-env=LOG_TOKENS,LOG_STREAM: npm:yaml reads both to decide whether to print debug output.
# Type-check, lint, and unit-test the Deno scripts
scripts-check:
    deno check scripts/ .agents/skills/github-project-workflow/scripts/
    deno lint scripts/ .agents/skills/github-project-workflow/scripts/
    deno test --allow-read --allow-write=/tmp --allow-run=git --allow-env=LOG_TOKENS,LOG_STREAM scripts/

# Validate feature layout, metadata, and version bumps against a base ref, and the label declaration
validate base="origin/main":
    ./scripts/validate.ts --base "$1"
    ./scripts/sync_labels.ts --check

# Strict-validate OpenSpec specs and changes; check config.yaml rules, feature options, and generated files
spec-check:
    OPENSPEC_NO_UPDATE_CHECK=1 OPENSPEC_TELEMETRY=0 openspec validate --all --strict --no-interactive
    ./scripts/check_openspec.ts

# List unarchived OpenSpec changes; --ready exits non-zero when one exists, the verdict the PR workflow reads
spec-status *args:
    ./scripts/check_spec_archived.ts "$@"

# Print the CI test plan for the current branch
affected base="origin/main":
    ./scripts/affected.ts --base "$1"

# Autogenerated + duplicate tests on the feature's compatibility images (--image, --preserve, --keep)
test feature *args:
    ./scripts/test_feature.ts --feature "$1" "${@:2}"

# Run a feature's scenario tests
test-scenarios feature *args:
    ./scripts/test_feature.ts --feature "$1" --mode scenarios "${@:2}"

# Run the cross-feature scenarios in test/_global
test-global *args:
    ./scripts/test_feature.ts --mode global "$@"

# Regenerate every feature's README.md and the feature list in the root README.md
docs:
    ./scripts/docs.ts

# Fail when a generated README.md or the root feature list is out of date, or README.zh.md lists other features
docs-check:
    ./scripts/docs.ts --check

# Scaffold src/<id> and test/<id> for a new feature (after its OpenSpec change exists); add --posix for POSIX sh
new-feature id *args:
    ./scripts/new_feature.ts "$1" "${@:2}"

# Print how the repository's labels differ from .github/labels.yml; --apply writes it (--keep-undeclared, --delete-used)
labels *args:
    ./scripts/sync_labels.ts "$@"

# Check a pull request title against the commit convention
check-title title:
    ./scripts/check_title.ts "$1"
