#!/bin/sh
# Autogenerated test: runs inside a container built from each compatibility image with apk-packages
# installed with default options (scenario "Omitted packages"): nothing is installed or recorded in
# apk's world, and nothing is left in /var/cache/apk or of the feature's directories. The same
# scenario on an image without apk is a direct check (direct_checks.ts).
# POSIX sh with its own check and reportResults: the Alpine images ship no bash, which the CLI's
# dev-container-features-test-lib needs.
set -eu

failed=0

check() {
  label=$1
  shift
  printf '\nTesting: %s\n' "$label"
  if "$@"; then
    echo "Passed: $label"
  else
    echo "FAILED: $label" >&2
    failed=$((failed + 1))
  fi
}

reportResults() {
  if [ "$failed" -ne 0 ]; then
    printf '\n%s check(s) failed\n' "$failed" >&2
    exit 1
  fi
  printf '\nAll checks passed\n'
}

not_installed() {
  ! apk info -e "$1" >/dev/null 2>&1
}

not_in_world() {
  ! grep -Fqx -- "$1" /etc/apk/world
}

cache_empty() {
  [ -z "$(ls -A /var/cache/apk)" ]
}

no_feature_dir() {
  for dir in "${TMPDIR:-/tmp}"/apk-packages.*; do
    [ ! -e "$dir" ] || return 1
  done
}

check "file (a proposals package) is not installed" not_installed file
check "tree (a proposals package) is not installed" not_installed tree
check "file is not in apk's world" not_in_world file
check "tree is not in apk's world" not_in_world tree
check "/var/cache/apk is empty" cache_empty
check "no directory of the feature is left" no_feature_dir

reportResults
