#!/bin/sh
# Autogenerated test: runs inside a container built from each compatibility image with apk-packages
# installed with default options (scenario "Omitted packages"): nothing is installed or recorded in
# apk's world, and nothing is left in /var/cache/apk or of the feature's temporary directories. The
# same scenario on an image without apk is a direct check (direct_checks.ts).
# POSIX sh with the stand-in in checks.sh: the Alpine images ship no bash, which the CLI's
# dev-container-features-test-lib needs.
set -eu

# shellcheck source=/dev/null
. "$(dirname "$0")/checks.sh"

not_installed() {
  ! apk info -e "$1" >/dev/null 2>&1
}

not_in_world() {
  ! grep -Fqx -- "$1" /etc/apk/world
}

check "file (a proposals package) is not installed" not_installed file
check "tree (a proposals package) is not installed" not_installed tree
check "file is not in apk's world" not_in_world file
check "tree is not in apk's world" not_in_world tree
check "/var/cache/apk is empty" cache_empty
check "no temporary directory of the feature is left" no_temporary_dir

reportResults
