#!/bin/sh
# Autogenerated test: runs inside a container built from each compatibility image with glab installed with default
# options (version latest). POSIX sh, because alpine:3.24 ships no bash.
set -eu

readonly LATEST_URL="https://gitlab.com/gitlab-org/cli/-/releases/permalink/latest"

# The path is computed from $0 at run time, so shellcheck cannot follow it.
# shellcheck source=/dev/null
. "$(dirname "$0")/checks.sh"

# The release the permanent link to the latest release names when the test runs, read as install.sh reads it,
# without following the redirect; a release between build and test fails once.
location="$(curl --proto '=https' --proto-redir '=https' --fail --silent --show-error --retry 3 \
  --head --output /dev/null --write-out '%{redirect_url}' "${LATEST_URL}")"
if [ -z "${location}" ]; then
  printf '%s did not redirect to a release\n' "${LATEST_URL}" >&2
  exit 1
fi
# The same parsing as install.sh: drop a query or fragment and a trailing slash, keep the last segment without "v".
latest="${location%%[?#]*}"
latest="${latest%/}"
latest="${latest##*/}"
latest="${latest#v}"

# Before glab runs at all: running glab as the remote user creates its configuration directory.
check "neither the remote user's nor root's home holds a glab configuration directory" no_glab_config

no_token_variables() {
  [ -z "${GITLAB_TOKEN+set}" ] && [ -z "${GITLAB_ACCESS_TOKEN+set}" ] && [ -z "${OAUTH_TOKEN+set}" ]
}
check "none of GITLAB_TOKEN, GITLAB_ACCESS_TOKEN, and OAUTH_TOKEN is set" no_token_variables

check "command -v glab resolves to /usr/local/bin/glab" glab_resolves_to_usr_local_bin
check "glab --version exits 0" glab_quiet --version
check "git --version exits 0" git --version
check "glab --version reports the release the permanent link to the latest release points to" \
  glab_reports_version "${latest}"

# No file under apt's package lists, dnf's cache, or apk's cache, whichever of them the image has.
package_caches_empty() {
  for package_caches_empty_dir in /var/lib/apt/lists /var/cache/libdnf5 /var/cache/apk; do
    if [ ! -d "${package_caches_empty_dir}" ]; then continue; fi
    package_caches_empty_files="$(as_root find "${package_caches_empty_dir}" -type f)" || return 1
    if [ -n "${package_caches_empty_files}" ]; then
      printf '  files remain under %s:\n%s\n' "${package_caches_empty_dir}" "${package_caches_empty_files}"
      return 1
    fi
  done
}
check "apt's package lists, dnf's cache, and apk's cache hold no file" package_caches_empty
check "no temporary directory or staged binary of the install remains" no_install_leftovers

reportResults
