#!/bin/sh
# Autogenerated test: runs inside a container built from each compatibility image with glab
# installed with default options (version latest). POSIX sh, because alpine:3.24 ships no bash.
set -e

# shellcheck source=/dev/null
. "$(dirname "$0")/checks.sh"

# Before glab runs at all: running glab as the remote user creates its configuration directory.
check "no glab configuration in the remote user's or root's home" no_glab_config
check "no token variable set" no_token_variables

check "glab resolves to /usr/local/bin/glab" glab_resolves_to_usr_local_bin
check "glab --version exits 0" glab_quiet --version
check "git --version exits 0" git --version
check "glab is the release the latest-release link names now" equals "$(installed_version)" "$(latest_version)"
check "package-manager caches are empty" package_caches_empty
check "no temporary files of the install remain" no_install_leftovers

reportResults
