#!/usr/bin/env bash
# Autogenerated test: runs inside a container built from each compatibility image with hf-mount
# installed with default options, as the image's remoteUser when its compatibility entry names one
# and as root otherwise. Scenarios "Omitted version", "Omitted backend", "Omitted
# installMountDependencies", "The installed daemon runs", "Downloads succeed", "NFS dependencies",
# "FUSE dependencies", and "Container starts with no mount". It makes no network request: `latest`
# can move between the build and the test, so only the form of the version is asserted.
set -e

# shellcheck source=/dev/null
source dev-container-features-test-lib

version_form() {
  hf-mount --version | grep -Eqx 'hf-mount [0-9]+\.[0-9]+\.[0-9]+'
}

# The canonical path is compared: on Fedora /usr/local/sbin is a link to /usr/local/bin and comes
# first on PATH, so `command -v` names the same file as /usr/local/sbin/hf-mount there.
resolves_to_installed_daemon() {
  [ "$(readlink -f "$(command -v hf-mount)")" = /usr/local/bin/hf-mount ]
}

# Root-owned and executable by every user, as the installer leaves each binary.
root_owned_0755() {
  [ "$(stat -c '%U:%G %a' "$1")" = "root:root 755" ]
}

same_release_as_daemon() {
  [ "$("$1" --version)" = "$(hf-mount --version)" ]
}

has_mount_nfs() {
  [ -x /sbin/mount.nfs ] || [ -x /usr/sbin/mount.nfs ] || command -v mount.nfs >/dev/null
}

# Read from /proc/*/comm, so the image needs no procps.
no_hf_mount_process() {
  local comm
  for comm in /proc/[0-9]*/comm; do
    case "$(cat "$comm" 2>/dev/null)" in
      hf-mount*) return 1 ;;
    esac
  done
}

status_reports_no_daemon() {
  hf-mount status 2>&1 | grep -q 'No running daemons'
}

no_user_allow_other() {
  ! grep -Eqs '^[[:space:]]*user_allow_other' /etc/fuse.conf
}

check "hf-mount --version reports hf-mount <MAJOR.MINOR.PATCH>" version_form
check "hf-mount resolves to /usr/local/bin/hf-mount" resolves_to_installed_daemon
for binary in hf-mount hf-mount-nfs hf-mount-fuse; do
  check "$binary is executable by this user" test -x "/usr/local/bin/$binary"
  check "$binary is owned by root with mode 0755" root_owned_0755 "/usr/local/bin/$binary"
done
check "hf-mount-nfs comes from the daemon's release" same_release_as_daemon hf-mount-nfs
check "hf-mount-fuse comes from the daemon's release" same_release_as_daemon hf-mount-fuse
check "hf-mount status exits 0" hf-mount status
check "hf-mount status reports no running daemon" status_reports_no_daemon
check "no hf-mount process runs" no_hf_mount_process
check "mount.nfs is present" has_mount_nfs
check "fusermount3 is on PATH" command -v fusermount3
check "no uncommented user_allow_other in /etc/fuse.conf" no_user_allow_other

reportResults
