#!/usr/bin/env bash
# Autogenerated test: runs inside a container built from each compatibility image with hf-mount installed with default
# options, as the image's remoteUser when its compatibility entry names one and as root otherwise. Scenarios "Omitted
# version", "Omitted backend", "Omitted installMountDependencies", "The installed daemon runs", "Downloads succeed",
# "NFS dependencies", "FUSE dependencies", and "Container starts with no mount". It makes no network request: `latest`
# can move between the build and the test, so only the form of the version is asserted.
set -euo pipefail

# shellcheck source=/dev/null
source dev-container-features-test-lib

# `hf-mount --version` succeeds and prints the one line "hf-mount <MAJOR.MINOR.PATCH>".
reports_major_minor_patch() {
  local output
  output="$(hf-mount --version)" || return
  [[ "${output}" =~ ^hf-mount\ [0-9]+\.[0-9]+\.[0-9]+$ ]]
}
check "hf-mount --version reports hf-mount <MAJOR.MINOR.PATCH>" reports_major_minor_patch

# The canonical path is compared: on fedora:44 /usr/local/sbin is a link to /usr/local/bin and comes first on PATH, so
# `command -v` prints /usr/local/sbin/hf-mount there.
resolves_to_usr_local_bin() {
  [[ "$(readlink -f "$(command -v hf-mount)")" == /usr/local/bin/hf-mount ]]
}
check "command -v hf-mount resolves, following symbolic links, to /usr/local/bin/hf-mount" resolves_to_usr_local_bin

# Stricter than the spec, which says owned by root and executable by every user: owner, group, and mode are compared
# with what install.sh gives each binary (root:root, mode 0755), so a binary left in any other state fails too.
root_owned_0755() {
  [[ "$(stat -c '%U:%G %a' "$1")" == "root:root 755" ]]
}
for binary in hf-mount hf-mount-nfs hf-mount-fuse; do
  check "${binary} is executable by the remote user" test -x "/usr/local/bin/${binary}"
  check "${binary} is owned by root and executable by every user" root_owned_0755 "/usr/local/bin/${binary}"
done

# `$1 --version` and `hf-mount --version` both succeed and print the same line. The expected release is read from the
# daemon at run time, not written as a literal: `latest` can move between the build and the test.
same_release_as_daemon() {
  local backend_version
  local daemon_version
  backend_version="$("$1" --version)" || return
  daemon_version="$(hf-mount --version)" || return
  [[ "${backend_version}" == "${daemon_version}" ]]
}
check "hf-mount-nfs comes from the same release as the daemon" same_release_as_daemon hf-mount-nfs
check "hf-mount-fuse comes from the same release as the daemon" same_release_as_daemon hf-mount-fuse

check "hf-mount status exits with status 0" hf-mount status

# "No running daemons" is what upstream's `hf-mount status` prints, to stderr, when no daemon runs.
status_reports_no_running_daemon() {
  local output
  output="$(hf-mount status 2>&1)" || return
  [[ "${output}" == *"No running daemons"* ]]
}
check "hf-mount status reports no running daemon" status_reports_no_running_daemon

# Read from /proc/*/comm, so the image needs no procps.
no_hf_mount_process() {
  local comm
  for comm in /proc/[0-9]*/comm; do
    # A process that ended after the glob was expanded has no comm file any more, and the container's keep-alive loop
    # starts a new `sleep 1` every second. cat's message for such a file is dropped, and its empty output matches
    # nothing.
    case "$(cat "${comm}" 2>/dev/null)" in
      hf-mount*) return 1 ;;
    esac
  done
}
check "no hf-mount process runs" no_hf_mount_process

has_mount_nfs() {
  if [[ -x /sbin/mount.nfs || -x /usr/sbin/mount.nfs ]]; then return 0; fi
  command -v mount.nfs >/dev/null
}
check "mount.nfs is present in /sbin, /usr/sbin, or on PATH" has_mount_nfs
check "fusermount3 is on PATH" command -v fusermount3

# fuse3, which the default options install, ships /etc/fuse.conf on every compatibility image.
no_user_allow_other() {
  ! grep -Eq '^[[:space:]]*user_allow_other' /etc/fuse.conf
}
check "/etc/fuse.conf holds no uncommented user_allow_other line" no_user_allow_other

reportResults
