#!/bin/sh
# Autogenerated test: runs inside a container built from each compatibility image with firewall installed with default
# options (defaultAction deny, presets github, failureMode closed, filterForward true), as the image's remote user
# (vscode on base:ubuntu24.04, root elsewhere). POSIX sh, because alpine:3.24 ships no bash.
set -eu

# The path is computed from $0 at run time, so shellcheck cannot follow it.
# shellcheck source=/dev/null
. "$(dirname "$0")/checks.sh"
# The feature's library as install.sh installed it: the validators that install.sh and apply.sh call. Its path exists
# only inside the image, so shellcheck cannot follow it.
# shellcheck source=/dev/null
. "${SHARE}/common.sh"

# What meta_ranges prints for the valid fixture below: its three distinct ranges as "<family> <prefix length> <CIDR>".
readonly VALID_RANGES="4 20 140.82.112.0/20
4 22 192.30.252.0/22
6 29 2a0a:a440:0:0:0:0:0:0/29"

work_dir="$(mktemp -d)"
# Why validate_options of common.sh rejected an option value.
reason=""

scripts_present() {
  [ -x "${SHARE}/apply.sh" ] && [ -x "${SHARE}/check.sh" ] && [ -f "${SHARE}/common.sh" ] && [ -f "${SHARE}/options" ]
}

# Whether nft is installed; the remote user's PATH may lack /usr/sbin.
nft_present() {
  if command -v nft; then return 0; fi
  [ -x /usr/sbin/nft ]
}

dnsmasq_has_nftset() {
  dnsmasq_has_nftset_version="$(dnsmasq --version)" || return 1
  awk '/^Compile time options:/ { for (i = 4; i <= NF; i++) if ($i == "nftset") found = 1 } END { exit !found }' <<EOF
${dnsmasq_has_nftset_version}
EOF
}

# Whether no file under the package managers' repository and key directories, whichever of them the image has, is
# named for the feature or mentions it.
no_feature_repository() {
  for no_feature_repository_dir in /etc/apt /etc/apk /etc/yum.repos.d /etc/pki/rpm-gpg /usr/share/keyrings; do
    if [ ! -d "${no_feature_repository_dir}" ]; then continue; fi
    no_feature_repository_named="$(find "${no_feature_repository_dir}" -iname '*firewall*')" || return 1
    if [ -n "${no_feature_repository_named}" ]; then
      printf 'named for the feature: %s\n' "${no_feature_repository_named}"
      return 1
    fi
    if no_feature_repository_mentions="$(grep -rlis firewall "${no_feature_repository_dir}")"; then
      printf 'mentions the feature: %s\n' "${no_feature_repository_mentions}"
      return 1
    fi
  done
}

no_sudoers_entry() {
  if as_root grep -rqis firewall /etc/sudoers /etc/sudoers.d; then return 1; fi
}

no_group_firewall() {
  if getent group firewall; then return 1; fi
}

not_in_group_dnsmasq() {
  not_in_group_dnsmasq_groups="$(id -nG)" || return 1
  case " ${not_in_group_dnsmasq_groups} " in
    *" dnsmasq "*) return 1 ;;
  esac
}

# Whether meta_ranges of common.sh, with which apply.sh validates the response of https://api.github.com/meta, prints
# every range of the valid fixture.
allows_every_listed_range() {
  allows_every_listed_range_found="$(meta_ranges "${work_dir}/valid.json")" || return 1
  printf '%s\n' "${allows_every_listed_range_found}"
  [ "${allows_every_listed_range_found}" = "${VALID_RANGES}" ]
}

# Whether meta_ranges rejects the response in the file $1, so that a start allows no range from it and is handled as
# a failure. Prints the reason.
response_rejected() {
  if response_rejected_reason="$(meta_ranges "$1")"; then return 1; fi
  printf '%s\n' "${response_rejected_reason}"
}

# Whether validate_options of common.sh, with whose reason install.sh fails the build, rejects the default options
# with the option $1 set to $2, in a message that names the entry $3 in double quotes. Prints the message.
option_rejected() {
  # validate_options reads the eight variables; shellcheck cannot see that, since it cannot follow common.sh.
  # shellcheck disable=SC2034
  (
    DEFAULTACTION="deny"
    PRESETS="github"
    ALLOWEDDOMAINS=""
    ALLOWEDCIDRS=""
    DENIEDDOMAINS=""
    DENIEDCIDRS=""
    FAILUREMODE="closed"
    FILTERFORWARD="true"
    case "$1" in
      presets) PRESETS="$2" ;;
      allowedDomains) ALLOWEDDOMAINS="$2" ;;
      allowedCidrs) ALLOWEDCIDRS="$2" ;;
      deniedDomains) DENIEDDOMAINS="$2" ;;
      deniedCidrs) DENIEDCIDRS="$2" ;;
    esac
    if validate_options; then exit 1; fi
    printf '%s\n' "${reason}"
    case "${reason}" in
      *"\"$3\""*) ;;
      *) exit 1 ;;
    esac
  )
}

default_options_recorded() {
  record_is defaultAction deny && record_is presets github && record_is failureMode closed \
    && record_is filterForward true
}

no_entry_recorded() {
  record_is allowedDomains "" && record_is allowedCidrs "" && record_is deniedDomains "" && record_is deniedCidrs ""
}

ranges_fetched() {
  ranges_fetched_recorded="$(record_field githubRanges)" || return 1
  case "${ranges_fetched_recorded}" in
    [0-9]*" ranges from https://api.github.com/meta") ;;
    *) return 1 ;;
  esac
}

# Whether no rule of the feature's table refuses an address, except the probe address 192.0.2.1 and the set of
# addresses learned for denied domains, which is empty without deniedDomains.
no_denied_entry() {
  no_denied_entry_table="$(table_listing)" || return 1
  awk '
    /daddr/ && /goto refuse/ && !/daddr 192\.0\.2\.1 / && !/@denied_learned/ { print "denied entry: " $0; found = 1 }
    END { exit found }' <<EOF
${no_denied_entry_table}
EOF
}

one_line_summary() {
  one_line_summary_output="$("${SHARE}/check.sh")" || return 1
  printf '%s\n' "${one_line_summary_output}"
  awk 'NF { lines++ } END { exit !(lines == 1 && NR == 1) }' <<EOF
${one_line_summary_output}
EOF
}

record_names_result_and_options() {
  cat "${RECORD}" && grep -q '^result=applied$' "${RECORD}" && grep -q '^presets=github$' "${RECORD}"
}

# Whether an attempt to append to the start record fails. The subshell keeps a failed redirection from ending the test.
cannot_write_record() {
  if (: >>"${RECORD}") 2>/dev/null; then return 1; fi
}

resolver_unprivileged() {
  resolver_unprivileged_pid="$(cat /run/firewall/dnsmasq.pid)" || return 1
  resolver_unprivileged_uid="$(awk '/^Uid:/ { print $2 }' "/proc/${resolver_unprivileged_pid}/status")" || return 1
  resolver_unprivileged_dnsmasq="$(id -u dnsmasq)" || return 1
  resolver_unprivileged_own="$(id -u)" || return 1
  printf 'the resolver runs as uid %s\n' "${resolver_unprivileged_uid}"
  [ "${resolver_unprivileged_uid}" = "${resolver_unprivileged_dnsmasq}" ] && [ "${resolver_unprivileged_uid}" != "0" ] \
    && [ "${resolver_unprivileged_uid}" != "${resolver_unprivileged_own}" ]
}

# Whether each of the files and directories $@ is owned by root and writable by neither its group nor others.
root_only_writable() {
  root_only_writable_modes="$(stat -c '%u %a %n' "$@")" || return 1
  awk '
    { group = substr($2, length($2) - 1, 1); other = substr($2, length($2), 1) }
    $1 != 0 || group ~ /[2367]/ || other ~ /[2367]/ { print "not writable by root only: " $0; bad = 1 }
    END { exit bad }' <<EOF
${root_only_writable_modes}
EOF
}

# Whether a connection to port 443 of the host $1 is refused in under one second. It goes to one address, the first
# that a lookup returns when the test runs, because curl makes one attempt per address of a name.
timed_refusal() {
  timed_refusal_address="$(first_address "$1")" || return 1
  if timed_refusal_seconds="$(curl -q -sS -o /dev/null --connect-timeout 5 -w '%{time_total}' \
    --resolve "$1:443:${timed_refusal_address}" "https://$1/")"; then
    return 1
  else
    timed_refusal_status=$?
  fi
  if [ "${timed_refusal_status}" -ne 7 ]; then return 1; fi
  printf 'refused after %s seconds\n' "${timed_refusal_seconds}"
  awk -v seconds="${timed_refusal_seconds}" 'BEGIN { exit !(seconds + 0 < 1) }'
}

# Whether github.com's address, the one a lookup returns when the test runs, is reachable without a lookup once the
# addresses learned for allowed domains are flushed, so that only a fetched range can allow it.
range_address_reachable() {
  range_address_reachable_address="$(first_address github.com)" || return 1
  as_root nft flush set inet firewall allowed_learned4 || return 1
  printf 'github.com at %s\n' "${range_address_reachable_address}"
  reachable --resolve "github.com:443:${range_address_reachable_address}" https://github.com/
}

# Supported image
check "the firewall's start-time scripts are present" scripts_present
check "the package nftables is present" nft_present
check "a dnsmasq build with nftables set support is present" dnsmasq_has_nftset
check "the package curl is present" command -v curl
check "the package jq is present" command -v jq

# No repository added, as far as a test can see it: no repository or key file names the feature.
check "no repository or key file names the feature" no_feature_repository

# No sudoers entry
check "no sudoers file was added for the remote user" no_sudoers_entry
check "no group was added for the feature" no_group_firewall
check "no group membership was added for the remote user" not_in_group_dnsmasq

# Metadata of a built container. Docker's default bounding set is 00000000a80425fb; CAP_NET_ADMIN is bit 12 (0x1000).
bounding_set="$(awk '/^CapBnd:/ { print $2 }' /proc/self/status)"
check "the container's capabilities are Docker's default plus NET_ADMIN, and it is not privileged" \
  [ "${bounding_set}" = "00000000a80435fb" ]

# Requirement: GitHub ranges, Implausible range, and Fetch fails (an invalid range): apply.sh validates the fetched
# response with meta_ranges and handles a rejected one as a failed start. The fixtures stand for the response.
printf '%s' '{"web":["192.30.252.0/22","2a0a:a440::/29"],"api":["140.82.112.0/20"],"git":["140.82.112.0/20"]}' \
  >"${work_dir}/valid.json"
printf '%s' '{"web":["192.30.252.1/22"],"api":[],"git":[]}' >"${work_dir}/host_bits.json"
printf '%s' '{"web":["10.0.0.0/7"],"api":[],"git":[]}' >"${work_dir}/short_ipv4.json"
printf '%s' '{"web":["2a00::/15"],"api":[],"git":[]}' >"${work_dir}/short_ipv6.json"
printf '%s' '{"web":["192.0.0.0/16"],"api":[],"git":[]}' >"${work_dir}/probe_address.json"
printf '%s' '{"web":["not-a-range"],"api":[],"git":[]}' >"${work_dir}/malformed_range.json"
printf '%s' '{"web":["140.82.112.0/"],"api":[],"git":[]}' >"${work_dir}/empty_prefix.json"
printf '%s' '{"web":[],"api":[]}' >"${work_dir}/missing_list.json"
printf '%s' 'not json' >"${work_dir}/not_json.json"
check "every IPv4 and IPv6 range in the response's web, api, and git lists is allowed" allows_every_listed_range
check "a response that lists a range with host bits set allows no range" \
  response_rejected "${work_dir}/host_bits.json"
check "a response that lists an IPv4 range shorter than the minimum prefix /8 allows no range" \
  response_rejected "${work_dir}/short_ipv4.json"
check "a response that lists an IPv6 range shorter than the minimum prefix /16 allows no range" \
  response_rejected "${work_dir}/short_ipv6.json"
check "a response that lists a range that contains 192.0.2.1 allows no range" \
  response_rejected "${work_dir}/probe_address.json"
check "a response that returns an invalid range allows no range" response_rejected "${work_dir}/malformed_range.json"
check "a response that returns a range with an empty prefix length allows no range" \
  response_rejected "${work_dir}/empty_prefix.json"
check "a malformed response that lacks one of the lists is a failure" response_rejected "${work_dir}/missing_list.json"
check "a malformed response that is not JSON is a failure" response_rejected "${work_dir}/not_json.json"

# The option values that fail a build, through the validator install.sh fails it with; the failing builds themselves
# are recorded in the pull request, since a test cannot run a build that must fail.
check "Unknown preset: presets with a name that is not a known preset is rejected with a message naming that entry" \
  option_rejected presets "github,nope" "nope"
check "Malformed CIDR: an allowedCidrs entry that is no address or CIDR is rejected with a message naming it" \
  option_rejected allowedCidrs "10.0.0.300" "10.0.0.300"
check "Malformed CIDR: an allowedCidrs entry with an empty prefix length is rejected with a message naming it" \
  option_rejected allowedCidrs "10.0.0.0/" "10.0.0.0/"
check "CIDR that cannot be applied as written: an entry with host bits set is rejected with a message naming it" \
  option_rejected allowedCidrs "10.0.0.1/8" "10.0.0.1/8"
check "CIDR that cannot be applied as written: 0.0.0.0/0, which contains 192.0.2.1, is rejected by name" \
  option_rejected allowedCidrs "0.0.0.0/0" "0.0.0.0/0"
check "an allowedDomains entry with a wildcard label is rejected with a message naming it" \
  option_rejected allowedDomains "*.example.com" "*.example.com"
check "an allowedDomains entry that is not a valid DNS name is rejected with a message naming it" \
  option_rejected allowedDomains "*" "*"
check "Malformed denied CIDR: a deniedCidrs entry that is no address or CIDR is rejected with a message naming it" \
  option_rejected deniedCidrs "10.0.0" "10.0.0"
check "Malformed denied CIDR: a deniedCidrs entry with an empty prefix length is rejected with a message naming it" \
  option_rejected deniedCidrs "2001:db8::/" "2001:db8::/"
check "Malformed denied CIDR: a deniedCidrs entry with host bits set is rejected with a message naming it" \
  option_rejected deniedCidrs "10.1.0.0/8" "10.1.0.0/8"
check "Malformed denied domain: a deniedDomains entry that is not a valid DNS name is rejected by name" \
  option_rejected deniedDomains "*.example.com" "*.example.com"

# First start
check "the current start is recorded as applied" record_current applied

# Omitted presets, and the other omitted options
check "without presets, the github preset is selected and no other" record_is presets github
check "the start record names the default options as the options in effect" default_options_recorded
check "without allowedDomains, allowedCidrs, deniedDomains, and deniedCidrs, the start record names no entry" \
  no_entry_recorded
# The number of ranges is GitHub's when the start fetched them, so the check matches any number.
check "with the github preset and defaultAction deny, the start fetched https://api.github.com/meta" ranges_fetched
check "without deniedDomains and deniedCidrs, no address is refused beyond what the other options refuse" \
  no_denied_entry

# Deviation from shell-style.md (Tests): this label uses the words of the design's Goal "Resolvers recorded once per
# container", an invariant of the approach that no scenario of the spec states.
check "after an applied start, /etc/resolv.conf names the local resolver" names_local_resolver

# Firewall in force
check "the check exits zero and prints a one-line summary" one_line_summary

# Remote user reads the record. Root, the remote user of three of the images, can write any file.
check "the start record names the result and the options in effect" record_names_result_and_options
if [ "$(id -u)" != "0" ]; then
  check "writing to the start record is denied" cannot_write_record
fi

# Resolver user
check "the resolver's process runs as the dnsmasq user, neither root nor the remote user" resolver_unprivileged

# Deviation from shell-style.md (Tests): this label uses the words of the design's Goal "Only root-owned inputs at
# start", an invariant of the approach that no scenario of the spec states.
check "every file the start-time script reads is owned by root and not writable by others" root_only_writable \
  "${SHARE}" "${SHARE}/options" "${SHARE}/common.sh" "${SHARE}/apply.sh" "${SHARE}/check.sh" /etc/resolv.conf \
  /var/lib/firewall /var/lib/firewall/resolvers /run/firewall "${RECORD}" /run/firewall/dnsmasq.conf \
  /run/firewall/dnsmasq.pid

# Allowed domain is reachable, GitHub preset
check "an HTTPS connection to github.com, which the github preset allows, succeeds" reachable https://github.com/
check "an HTTPS connection to api.github.com, which the github preset allows, succeeds" \
  reachable https://api.github.com/

# Unlisted name still resolves; Unlisted domain is refused, Omitted defaultAction, Omitted allowedDomains
check "a lookup of registry.npmjs.org, which no option allows, returns its addresses" resolves registry.npmjs.org
check "a connection to registry.npmjs.org, which no option allows, fails with an error" \
  refused https://registry.npmjs.org/
check "a refused connection fails immediately: in under one second" timed_refusal registry.npmjs.org

# Other DNS server refused: over TCP, so that the refusal shows as a refused connection.
check "a DNS connection to 8.8.8.8, a public resolver that /etc/resolv.conf did not name, is refused" \
  refused http://8.8.8.8:53/

# Ranges loaded
check "an address inside a git range is reachable without a DNS lookup of a GitHub name" range_address_reachable

rm -rf "${work_dir}"
reportResults
