#!/bin/sh
# Autogenerated test: runs inside a container built from each compatibility image with firewall
# installed with default options (defaultAction deny, presets github, failureMode closed,
# filterForward true), as the image's remote user (vscode on base:ubuntu-24.04, root elsewhere).
# POSIX sh: Alpine ships no bash (helpers.sh).

# shellcheck source=/dev/null
. "$(dirname "$0")/helpers.sh"

TMP=$(mktemp -d)

# --- Build time ---

# Supported image
check "start-time scripts and options installed" \
  test -x "$SHARE/apply.sh" -a -x "$SHARE/check.sh" -a -f "$SHARE/common.sh" -a -f "$SHARE/options"
check "nftables installed" sh -c 'command -v nft || test -x /usr/sbin/nft'
has_nftset() {
  dnsmasq --version | awk '/^Compile time options:/ { for (i = 4; i <= NF; i++) if ($i == "nftset") ok = 1 }
    END { exit !ok }'
}
check "dnsmasq with nftset support installed" has_nftset
check "curl and jq installed" sh -c 'command -v curl && command -v jq'

# No repository added: no repository or key file names the feature.
no_feature_repository() {
  for dir in /etc/apt /etc/apk /etc/yum.repos.d /etc/pki/rpm-gpg /usr/share/keyrings; do
    [ -d "$dir" ] || continue
    if find "$dir" -iname '*firewall*' | grep -q .; then return 1; fi
    if grep -rqis firewall "$dir"; then return 1; fi
  done
}
check "no repository or signing key added" no_feature_repository

# No sudoers entry
no_sudoers_entry() {
  ! as_root grep -rqis firewall /etc/sudoers /etc/sudoers.d
}
check "no sudoers entry names the feature" no_sudoers_entry
check "no firewall group" sh -c '! getent group firewall'
check "remote user not in the dnsmasq group" sh -c '! id -nG | tr " " "\n" | grep -qx dnsmasq'

# Metadata of a built container: Docker's default bounding set plus NET_ADMIN, not privileged.
check "capabilities are Docker's default plus NET_ADMIN" \
  test "$(awk '/^CapBnd:/ { print $2 }' /proc/self/status)" = 00000000a80435fb

# Implausible range: the range validator against fixture responses of https://api.github.com/meta.
printf '%s' '{"web":["192.30.252.0/22","2a0a:a440::/29"],"api":["140.82.112.0/20"],"git":["140.82.112.0/20"]}' \
  >"$TMP/valid.json"
printf '%s' '{"web":["192.30.252.1/22"],"api":[],"git":[]}' >"$TMP/host-bits.json"
printf '%s' '{"web":["10.0.0.0/7"],"api":[],"git":[]}' >"$TMP/short-ipv4.json"
printf '%s' '{"web":["2a00::/15"],"api":[],"git":[]}' >"$TMP/short-ipv6.json"
printf '%s' '{"web":["192.0.0.0/16"],"api":[],"git":[]}' >"$TMP/probe-address.json"
printf '%s' '{"web":["not-a-range"],"api":[],"git":[]}' >"$TMP/malformed-range.json"
printf '%s' '{"web":["140.82.112.0/"],"api":[],"git":[]}' >"$TMP/empty-prefix.json"
printf '%s' '{"web":[],"api":[]}' >"$TMP/missing-list.json"
printf '%s' 'not json' >"$TMP/not-json.json"
meta_ranges() {
  (
    # shellcheck source=/dev/null
    . "$SHARE/common.sh"
    fw_meta_ranges "$1"
  )
}
meta_rejected() {
  ! meta_ranges "$1" >/dev/null
}
check "fixture: a valid response yields its three distinct ranges" \
  test "$(meta_ranges "$TMP/valid.json" | wc -l | tr -d ' ')" = 3
for fixture in host-bits short-ipv4 short-ipv6 probe-address malformed-range empty-prefix missing-list not-json; do
  check "fixture: $fixture is rejected" meta_rejected "$TMP/$fixture.json"
done

# The option validator install.sh runs (the builds that must fail are recorded in the PR).
# shellcheck disable=SC2034 # the OPT_* values are read by fw_validate_options
options_rejected() {
  (
    # shellcheck source=/dev/null
    . "$SHARE/common.sh"
    OPT_DEFAULT_ACTION=deny OPT_PRESETS=github OPT_ALLOWED_DOMAINS='' OPT_ALLOWED_CIDRS=''
    OPT_DENIED_DOMAINS='' OPT_DENIED_CIDRS='' OPT_FAILURE_MODE=closed OPT_FILTER_FORWARD=true
    eval "$1=\$2"
    ! fw_validate_options && echo "$FW_ERROR" && case $FW_ERROR in *"\"$3\""*) ;; *) false ;; esac
  )
}
check "validator: unknown preset" options_rejected OPT_PRESETS github,nope nope
check "validator: malformed CIDR" options_rejected OPT_ALLOWED_CIDRS 10.0.0.300 10.0.0.300
check "validator: CIDR with host bits" options_rejected OPT_ALLOWED_CIDRS 10.0.0.1/8 10.0.0.1/8
check "validator: 0.0.0.0/0 allowed" options_rejected OPT_ALLOWED_CIDRS 0.0.0.0/0 0.0.0.0/0
check "validator: wildcard domain" options_rejected OPT_ALLOWED_DOMAINS '*.example.com' '*.example.com'
check "validator: * alone" options_rejected OPT_ALLOWED_DOMAINS '*' '*'
check "validator: CIDR with empty prefix" options_rejected OPT_ALLOWED_CIDRS 10.0.0.0/ 10.0.0.0/
check "validator: malformed denied CIDR" options_rejected OPT_DENIED_CIDRS 10.0.0 10.0.0
check "validator: denied CIDR with empty prefix" options_rejected OPT_DENIED_CIDRS 2001:db8::/ 2001:db8::/
check "validator: denied CIDR with host bits" options_rejected OPT_DENIED_CIDRS 10.1.0.0/8 10.1.0.0/8
check "validator: wildcard denied domain" options_rejected OPT_DENIED_DOMAINS '*.example.com' '*.example.com'

# --- Start ---

# First start, Omitted presets and the other omitted options.
check "the current start is recorded as applied" record_current applied
defaults_recorded() {
  record_is defaultAction deny && record_is presets github && record_is failureMode closed \
    && record_is filterForward true
}
check "record: the default options are in effect" defaults_recorded
no_entry_recorded() {
  record_is allowedDomains '' && record_is allowedCidrs '' && record_is deniedDomains '' && record_is deniedCidrs ''
}
check "record: no allowed or denied entry beyond the presets" no_entry_recorded
ranges_recorded() {
  case $(record_field githubRanges) in
    [0-9]*" ranges from https://api.github.com/meta") ;;
    *) return 1 ;;
  esac
}
check "record: GitHub ranges fetched" ranges_recorded
no_denied_entry() {
  table_listing | grep 'goto refuse' | grep 'daddr' | grep -v -e 192.0.2.1 -e @denied_learned | grep -q . && return 1
  return 0
}
check "ruleset: no denied entry" no_denied_entry
check "resolv.conf names only the feature's resolver" names_local_resolver

# Firewall in force, Remote user reads the record
check_output() {
  out=$("$SHARE/check.sh") || return 1
  echo "$out"
  [ "$(printf '%s\n' "$out" | wc -l | tr -d ' ')" = 1 ]
}
check "the start check passes with a one-line summary" check_output
reads_record() {
  cat "$RECORD" && grep -q '^result=applied$' "$RECORD" && grep -q '^presets=github$' "$RECORD"
}
check "the remote user reads the record" reads_record
if [ "$(id -u)" != 0 ]; then
  cannot_write_record() {
    ! sh -c ': >>"$1"' _ "$RECORD" 2>/dev/null
  }
  check "the remote user cannot write the record" cannot_write_record
fi

# Resolver user
resolver_unprivileged() {
  uid=$(awk '/^Uid:/ { print $2 }' "/proc/$(cat /run/firewall/dnsmasq.pid)/status") || return 1
  echo "dnsmasq runs as uid $uid"
  [ "$uid" = "$(id -u dnsmasq)" ] && [ "$uid" != 0 ] && [ "$uid" != "$(id -u)" ]
}
check "the resolver runs as the dnsmasq user" resolver_unprivileged

# Every file the start-time script reads is owned by root and writable by no one else.
root_only_writable() {
  stat -c '%u %a %n' "$@" | awk '
    { g = substr($2, length($2) - 1, 1); o = substr($2, length($2), 1) }
    $1 != 0 || g ~ /[2367]/ || o ~ /[2367]/ { print "not root-only: " $0; bad = 1 }
    END { exit bad }'
}
check "start-time inputs are writable by root only" root_only_writable \
  "$SHARE" "$SHARE/options" "$SHARE/common.sh" "$SHARE/apply.sh" "$SHARE/check.sh" /etc/resolv.conf \
  /var/lib/firewall /var/lib/firewall/resolvers /run/firewall "$RECORD" /run/firewall/dnsmasq.conf

# Allowed domain is reachable, GitHub preset
check "github.com reachable" reachable https://github.com/
check "api.github.com reachable" reachable https://api.github.com/

# Unlisted domain is refused, Unlisted name still resolves, Omitted defaultAction
check "registry.npmjs.org resolves" resolves registry.npmjs.org
check "registry.npmjs.org refused" refused https://registry.npmjs.org/
check "a refused connection fails in under a second" timed_refusal registry.npmjs.org

# Other DNS server refused
check "TCP to 8.8.8.8 port 53 refused" refused http://8.8.8.8:53/

# Ranges loaded: with the learned addresses flushed, github.com's address (inside the git ranges)
# is still reachable without a lookup.
ranges_loaded() {
  address=$(first_address github.com) || return 1
  as_root nft flush set inet firewall allowed_learned4 || return 1
  echo "github.com at $address"
  reachable --resolve "github.com:443:$address" https://github.com/
}
check "a GitHub range address is reachable without a lookup" ranges_loaded

rm -rf "$TMP"
reportResults
