#!/usr/bin/env bash
# Autogenerated test: runs inside a container built from each compatibility image with pacman-packages
# installed with default options (scenario "Omitted packages"): nothing is installed and no sync
# database is downloaded. The same scenario on an image without pacman is a direct check
# (direct_checks.ts).
set -e

# shellcheck source=/dev/null
source dev-container-features-test-lib

not_installed() {
  ! pacman -Qq "$1" >/dev/null 2>&1
}

no_sync_databases() {
  [ -z "$(find /var/lib/pacman/sync -mindepth 1 -print -quit)" ]
}

check "bc (a proposals package) is not installed" not_installed bc
check "tree (a proposals package) is not installed" not_installed tree
check "no sync database was downloaded" no_sync_databases

reportResults
