#!/usr/bin/env bash
# Autogenerated test: apt-packages installed with default options on each compatibility image. Spec scenario "Omitted
# packages": the feature installs nothing and does not refresh the package index. The same scenario on an image without
# apt-get is checked by the scenario fail_image_without_apt_get.
set -euo pipefail

# shellcheck source=/dev/null
source dev-container-features-test-lib

not_installed() {
  [[ "$(dpkg-query -W -f='${Status}' "$1" 2>/dev/null)" != "install ok installed" ]]
}

# Both compatibility images ship no package index, so a package list found here was fetched by the feature.
no_index() {
  ! compgen -G '/var/lib/apt/lists/*_Packages*' >/dev/null
}

check "the feature installs nothing: bc is not installed" not_installed bc
check "the feature installs nothing: file is not installed" not_installed file
check "the feature does not refresh the package index" no_index

reportResults
