#!/usr/bin/env bash
# Autogenerated test: runs inside a container built from each compatibility image with apt-packages
# installed with default options (scenario "Omitted packages"): nothing is installed and no package
# index is left behind. The same scenario on an image without apt-get is a direct check
# (direct_checks.ts).
set -e

# shellcheck source=/dev/null
source dev-container-features-test-lib

not_installed() {
  [ "$(dpkg-query -W -f='${Status}' "$1" 2>/dev/null)" != "install ok installed" ]
}

no_index() {
  ! compgen -G '/var/lib/apt/lists/*_Packages*' >/dev/null
}

check "bc (a proposals package) is not installed" not_installed bc
check "file (a proposals package) is not installed" not_installed file
check "no package index was left" no_index

reportResults
