// Shared model of the feature collection: features, their in-repo dependencies, compatibility
// lists, and test scenarios. The loaders read the working tree and git() runs git for the scripts
// that need history; everything else is pure so the selection logic can be unit-tested without a
// repository.
import { join } from "jsr:@std/path@1.1.6";
import { parse as parseJsonc } from "jsr:@std/jsonc@1.0.3";

/** GitHub repository, which is also the OCI namespace path the features are published under. */
export const REPO = "hoshiori-dev/devcontainer-features";

/** OCI namespace every feature of this repository is published under. */
export const NAMESPACE = `ghcr.io/${REPO}`;

/** A publishable feature version: MAJOR.MINOR.PATCH without a pre-release or build suffix. */
export const RELEASE_VERSION = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/;

/** GitHub-hosted runner label for each architecture a compatibility entry may name. */
export const RUNNERS = { amd64: "ubuntu-24.04", arm64: "ubuntu-24.04-arm" } as const;
export type Arch = keyof typeof RUNNERS;

/** Default feature scenario architecture and fixed global scenario architecture. */
export const SCENARIO_ARCH: Arch = "amd64";

/** Repository paths whose change can break feature testing itself; they select the canary set. */
export const INFRA_PATHS = [
    ".github/workflows/ci.yml",
    "deno.json",
    ".github/actions/",
    "scripts/lib/",
    "scripts/affected.ts",
    "scripts/test_feature.ts",
    "test/canary.json",
    "test/compatibility.schema.json",
];

/** GitHub's per-workflow-run limit on jobs generated by one matrix. */
export const MATRIX_LIMIT = 256;

export interface CompatEntry {
    image: string;
    arch?: Arch[];
    remoteUser?: string;
}

export interface Compat {
    images: CompatEntry[];
    scenarioArchitectures?: Arch[];
    idempotencyExemption?: string;
}

export interface Scenario {
    name: string;
    image?: string;
    usesBuild: boolean;
    /** Feature keys exactly as written in scenarios.json. */
    featureKeys: string[];
}

export interface FeatureInfo {
    id: string;
    /** Parsed devcontainer-feature.json, or undefined when it could not be read. */
    json?: Record<string, unknown>;
    jsonError?: string;
    /** In-repo feature ids named in dependsOn. */
    dependsOn: string[];
    /** In-repo feature ids named in installsAfter. */
    installsAfter: string[];
    /** In-repo feature ids installed by this feature's test scenarios. */
    scenarioRefs: string[];
    scenarios: Scenario[];
    compat?: Compat;
    compatError?: string;
    scenariosError?: string;
}

/** A problem tied to one repository file, with a message that says how to fix it. */
export interface Problem {
    file: string;
    message: string;
}

export interface RepoModel {
    features: Map<string, FeatureInfo>;
    /** In-repo feature ids installed by test/_global scenarios. */
    globalRefs: string[];
    globalScenarios: Scenario[];
    hasGlobal: boolean;
    canary: string[];
    /** Files outside src/<id> and test/<id> that could not be read (global scenarios, canary list). */
    errors: Problem[];
}

/** Returns the feature id when `ref` points into this repository's OCI namespace. */
export function inRepoId(ref: string): string | undefined {
    const prefix = `${NAMESPACE}/`;
    if (!ref.toLowerCase().startsWith(prefix)) return undefined;
    const match = /^([a-z0-9]+(?:[._-][a-z0-9]+)*)(?:[:@].*)?$/.exec(ref.slice(prefix.length));
    return match?.[1];
}

/** Resolves a scenario feature key: a bare key names src/<key> (existing or not), a full ref may be in-repo. */
export function scenarioKeyId(key: string): string | undefined {
    return key.includes("/") ? inRepoId(key) : key;
}

/** Major version of a feature's metadata, or undefined when its version is not a release version. */
export function majorOf(feature: FeatureInfo | undefined): number | undefined {
    const version = feature?.json?.version;
    const match = typeof version === "string" ? RELEASE_VERSION.exec(version) : null;
    return match ? Number(match[1]) : undefined;
}

function unique<T>(items: Iterable<T>): T[] {
    return [...new Set(items)];
}

/** Reference strings of a dependsOn object, an installsAfter array, or a scenario's features object. */
export function refsOf(value: unknown): string[] {
    if (Array.isArray(value)) return value.filter((v): v is string => typeof v === "string");
    if (value && typeof value === "object") return Object.keys(value);
    return [];
}

/** In-repo feature ids referenced by a dependsOn object or installsAfter array. */
export function inRepoRefs(value: unknown): string[] {
    return unique(refsOf(value).map(inRepoId).filter((id): id is string => id !== undefined));
}

/** References in a dependsOn object or installsAfter array that are local paths instead of OCI refs. */
export function localPathRefs(value: unknown): string[] {
    return refsOf(value).filter((ref) => /^(\.{1,2}(\/|$)|\/)/.test(ref));
}

export function parseScenarios(value: unknown): Scenario[] {
    if (!value || typeof value !== "object" || Array.isArray(value)) {
        throw new Error("scenarios.json must be an object mapping scenario names to dev container configs");
    }
    return Object.entries(value as Record<string, unknown>).map(([name, raw]) => {
        const config = (raw ?? {}) as Record<string, unknown>;
        return {
            name,
            image: typeof config.image === "string" ? config.image : undefined,
            usesBuild: config.build !== undefined,
            featureKeys: refsOf(config.features),
        };
    });
}

/** Architectures selected for all of a feature's scenario tests. */
export function scenarioArchesOf(compat: Compat): Arch[] {
    return compat.scenarioArchitectures ?? [SCENARIO_ARCH];
}

/** Default architecture list of a compatibility entry. */
export function archesOf(entry: CompatEntry): Arch[] {
    return entry.arch ?? ["amd64"];
}

// ---------------------------------------------------------------------------------------------
// Loaders
// ---------------------------------------------------------------------------------------------

export function parseJsoncText(text: string): unknown {
    return parseJsonc(text);
}

/** Runs git in `cwd`; `ok` is false when it exits non-zero, and `err` carries its message. */
export async function runGit(args: string[], cwd = "."): Promise<{ ok: boolean; out: string; err: string }> {
    const output = await new Deno.Command("git", { args, cwd, stdout: "piped", stderr: "piped" }).output();
    const decode = (bytes: Uint8Array) => new TextDecoder().decode(bytes);
    return { ok: output.success, out: decode(output.stdout), err: decode(output.stderr).trim() };
}

/** Runs git and returns its output; throws with git's own message when it fails. */
export async function git(args: string[]): Promise<string> {
    const result = await runGit(args);
    if (!result.ok) throw new Error(`git ${args.join(" ")} failed: ${result.err || "no message"}`);
    return result.out;
}

export async function readJsonc(path: string): Promise<unknown> {
    return parseJsoncText(await Deno.readTextFile(path));
}

export async function exists(path: string): Promise<boolean> {
    try {
        await Deno.stat(path);
        return true;
    } catch (error) {
        if (error instanceof Deno.errors.NotFound) return false;
        throw error;
    }
}

/** Names of the directories directly under `path`, sorted; none when `path` does not exist. */
export async function listDirs(path: string): Promise<string[]> {
    if (!(await exists(path))) return [];
    const names: string[] = [];
    for await (const entry of Deno.readDir(path)) if (entry.isDirectory) names.push(entry.name);
    return names.sort();
}

/** One compiled validator per repository root, since each root has its own schema file. */
const compatValidators = new Map<string, (value: unknown) => string | undefined>();

/** Validates a parsed compatibility.json against `<root>/test/compatibility.schema.json`. */
export async function compatSchemaErrors(root: string, value: unknown): Promise<string | undefined> {
    let validator = compatValidators.get(root);
    if (!validator) {
        const schema = await readJsonc(join(root, "test", "compatibility.schema.json")) as Record<string, unknown>;
        // Loaded on first use, so scripts that never validate — tag_releases in the Release job, with its write
        // token — never evaluate the npm package or its unpinned transitive dependencies.
        const { default: Ajv } = await import("npm:ajv@8.20.0");
        // deno-lint-ignore no-explicit-any
        const ajv = new (Ajv as any)({ allErrors: true, strict: false });
        const validate = ajv.compile(schema);
        validator = (candidate) =>
            validate(candidate)
                ? undefined
                : ajv.errorsText(validate.errors, { dataVar: "compatibility.json", separator: "; " });
        compatValidators.set(root, validator);
    }
    return validator(value);
}

export async function loadFeature(root: string, id: string): Promise<FeatureInfo> {
    const info: FeatureInfo = { id, dependsOn: [], installsAfter: [], scenarioRefs: [], scenarios: [] };
    try {
        info.json = await readJsonc(join(root, "src", id, "devcontainer-feature.json")) as Record<string, unknown>;
        info.dependsOn = inRepoRefs(info.json.dependsOn);
        info.installsAfter = inRepoRefs(info.json.installsAfter);
    } catch (error) {
        info.jsonError = error instanceof Error ? error.message : String(error);
    }
    const compatPath = join(root, "test", id, "compatibility.json");
    if (!(await exists(compatPath))) {
        info.compatError = "missing";
    } else {
        try {
            const compat = await readJsonc(compatPath);
            const problem = await compatSchemaErrors(root, compat);
            if (problem) info.compatError = problem;
            else info.compat = compat as Compat;
        } catch (error) {
            info.compatError = error instanceof Error ? error.message : String(error);
        }
    }
    const scenariosPath = join(root, "test", id, "scenarios.json");
    if (await exists(scenariosPath)) {
        try {
            info.scenarios = parseScenarios(await readJsonc(scenariosPath));
        } catch (error) {
            info.scenariosError = error instanceof Error ? error.message : String(error);
        }
    }
    return info;
}

function scenarioRefs(scenarios: Scenario[]): string[] {
    return unique(
        scenarios.flatMap((s) => s.featureKeys).map(scenarioKeyId).filter((ref): ref is string => ref !== undefined),
    );
}

function errorText(error: unknown): string {
    return error instanceof Error ? error.message : String(error);
}

/**
 * Loads every feature under src/ plus the global scenarios and the canary list. Unreadable files never throw:
 * they surface as FeatureInfo errors or in `errors`, so every caller can name the file to fix.
 */
export async function loadRepo(root: string): Promise<RepoModel> {
    const features = new Map<string, FeatureInfo>();
    for (const id of await listDirs(join(root, "src"))) features.set(id, await loadFeature(root, id));
    for (const feature of features.values()) {
        feature.scenarioRefs = scenarioRefs(feature.scenarios).filter((ref) => ref !== feature.id);
    }
    const errors: Problem[] = [];
    const globalPath = join(root, "test", "_global", "scenarios.json");
    const hasGlobal = await exists(globalPath);
    let globalScenarios: Scenario[] = [];
    if (hasGlobal) {
        try {
            globalScenarios = parseScenarios(await readJsonc(globalPath));
        } catch (error) {
            errors.push({ file: "test/_global/scenarios.json", message: `unreadable: ${errorText(error)}.` });
        }
    }
    const canaryPath = join(root, "test", "canary.json");
    let canary: string[] = [];
    if (await exists(canaryPath)) {
        try {
            const value = await readJsonc(canaryPath);
            const list = value !== null && typeof value === "object" && !Array.isArray(value)
                ? (value as { features?: unknown }).features ?? []
                : undefined;
            if (!Array.isArray(list) || !list.every((id) => typeof id === "string")) {
                throw new Error('it must be {"features": ["<id>", ...]}');
            }
            canary = list;
        } catch (error) {
            errors.push({ file: "test/canary.json", message: `unreadable: ${errorText(error)}.` });
        }
    }
    return { features, globalRefs: scenarioRefs(globalScenarios), globalScenarios, hasGlobal, canary, errors };
}

/** Every test file the model could not read: scenario files, the global scenarios, the canary list. */
export function unreadableFiles(model: RepoModel): Problem[] {
    return [
        ...[...model.features.values()].flatMap((f) =>
            f.scenariosError
                ? [{ file: `test/${f.id}/scenarios.json`, message: `unreadable: ${f.scenariosError}.` }]
                : []
        ),
        ...model.errors,
    ];
}

// ---------------------------------------------------------------------------------------------
// Graph and selection (pure)
// ---------------------------------------------------------------------------------------------

/**
 * `ids` plus every in-repo feature they reach through dependsOn and installsAfter, transitively: what a test of
 * `ids` must be able to resolve. The CLI fetches the metadata of every installsAfter entry, so those count too.
 */
export function installClosure(model: RepoModel, ids: Iterable<string>): string[] {
    const seen = new Set<string>();
    const queue = [...ids];
    while (queue.length > 0) {
        const id = queue.shift()!;
        if (seen.has(id) || !model.features.has(id)) continue;
        seen.add(id);
        const feature = model.features.get(id)!;
        queue.push(...feature.dependsOn, ...feature.installsAfter);
    }
    return [...seen].sort();
}

/**
 * Finds one cycle through dependsOn and installsAfter, returned as the ids along it, or undefined when there is
 * none. The CLI orders both kinds of edge together, so a loop mixing them cannot be installed either.
 */
export function findInstallCycle(model: RepoModel): string[] | undefined {
    const state = new Map<string, "visiting" | "done">();
    const stack: string[] = [];
    const visit = (id: string): string[] | undefined => {
        if (state.get(id) === "done") return undefined;
        if (state.get(id) === "visiting") return [...stack.slice(stack.indexOf(id)), id];
        state.set(id, "visiting");
        stack.push(id);
        const feature = model.features.get(id);
        for (const dep of unique([...(feature?.dependsOn ?? []), ...(feature?.installsAfter ?? [])])) {
            if (!model.features.has(dep)) continue;
            const cycle = visit(dep);
            if (cycle) return cycle;
        }
        stack.pop();
        state.set(id, "done");
        return undefined;
    };
    for (const id of model.features.keys()) {
        const cycle = visit(id);
        if (cycle) return cycle;
    }
    return undefined;
}

export type PathKind =
    /** `part` is "src" for what ships in the feature's artifact, "test" for its tests. */
    | { kind: "feature"; id: string; part: "src" | "test" }
    | { kind: "global" }
    | { kind: "infra" }
    | { kind: "other" };

export function classifyPath(path: string): PathKind {
    const parts = path.split("/");
    if (parts[0] === "src" && parts.length > 2) return { kind: "feature", id: parts[1], part: "src" };
    if (parts[0] === "test" && parts.length > 2) {
        if (parts[1] === "_global") return { kind: "global" };
        if (!parts[1].startsWith("_")) return { kind: "feature", id: parts[1], part: "test" };
    }
    if (INFRA_PATHS.some((p) => (p.endsWith("/") ? path.startsWith(p) : path === p))) return { kind: "infra" };
    return { kind: "other" };
}

export interface Selection {
    /** Affected feature id → why it was selected. */
    reasons: Map<string, string>;
    runGlobal: boolean;
}

/**
 * Selects the features a set of changed paths affects. A change under src/<id> changes what users install, so it also
 * selects every feature that installs <id> through dependsOn or installsAfter — transitively, since their installed
 * result changes too — and every feature whose scenarios install one of those, without following that feature's own
 * dependents: its artifact did not change. A change under test/<id> selects only <id>. A changed id no longer in src/
 * (a deleted or renamed feature) selects nothing itself but still selects what references it. A test infrastructure
 * change adds the canaries and runs the global scenarios, so both test paths run through the changed pipeline.
 */
export function selectAffected(changed: string[], model: RepoModel): Selection {
    const reasons = new Map<string, string>();
    /** Ids whose installed result may differ: changed src/ trees and everything installing them. */
    const shipped = new Set<string>();
    let globalChanged = false;
    let infraChanged = false;
    for (const path of changed) {
        const kind = classifyPath(path);
        if (kind.kind === "feature") {
            if (model.features.has(kind.id)) reasons.set(kind.id, "changed");
            if (kind.part === "src") shipped.add(kind.id);
        } else if (kind.kind === "global") globalChanged = true;
        else if (kind.kind === "infra") infraChanged = true;
    }
    const installers = new Map<string, string[]>();
    const testers = new Map<string, string[]>();
    for (const feature of model.features.values()) {
        for (const dep of new Set([...feature.dependsOn, ...feature.installsAfter])) {
            if (dep !== feature.id) installers.set(dep, [...(installers.get(dep) ?? []), feature.id]);
        }
        for (const dep of feature.scenarioRefs) testers.set(dep, [...(testers.get(dep) ?? []), feature.id]);
    }
    const why = (id: string, verb: string) => model.features.has(id) ? `${verb} ${id}` : `references removed ${id}`;
    const queue = [...shipped];
    while (queue.length > 0) {
        const id = queue.shift()!;
        for (const dependent of installers.get(id) ?? []) {
            if (shipped.has(dependent)) continue;
            shipped.add(dependent);
            if (!reasons.has(dependent)) reasons.set(dependent, why(id, "depends on"));
            queue.push(dependent);
        }
    }
    for (const id of [...shipped].sort()) {
        for (const tester of testers.get(id) ?? []) {
            if (!reasons.has(tester)) reasons.set(tester, why(id, "tests with"));
        }
    }
    // Canaries exercise the pipeline itself; their dependents are not pulled in, keeping the set bounded.
    if (infraChanged) {
        for (const id of model.canary) if (model.features.has(id) && !reasons.has(id)) reasons.set(id, "canary");
    }
    const runGlobal = model.hasGlobal &&
        (globalChanged || infraChanged || model.globalRefs.some((id) => shipped.has(id)));
    return { reasons, runGlobal };
}

export interface TestJob {
    feature: string;
    image: string;
    arch: Arch;
    runner: string;
    remoteUser: string;
}

export interface Plan {
    tests: TestJob[];
    scenarios: { feature: string; arch: Arch; runner: string }[];
    runGlobal: boolean;
    reasons: Record<string, string>;
}

/** Expands a selection into CI matrices; throws with a fix-it message on unusable input. */
export function buildPlan(selection: Selection, model: RepoModel): Plan {
    const tests: TestJob[] = [];
    const scenarios: Plan["scenarios"] = [];
    for (const id of [...selection.reasons.keys()].sort()) {
        const feature = model.features.get(id)!;
        if (!feature.compat) {
            throw new Error(
                `test/${id}/compatibility.json is ${feature.compatError === "missing" ? "missing" : "invalid"}` +
                    (feature.compatError && feature.compatError !== "missing" ? ` (${feature.compatError})` : "") +
                    ". CI cannot know which images to test the feature on. Fix the file; see .agents/knowledge/testing.md.",
            );
        }
        for (const entry of feature.compat.images) {
            for (const arch of archesOf(entry)) {
                tests.push({
                    feature: id,
                    image: entry.image,
                    arch,
                    runner: RUNNERS[arch],
                    remoteUser: entry.remoteUser ?? "",
                });
            }
        }
        if (feature.scenarios.length > 0) {
            for (const arch of scenarioArchesOf(feature.compat)) {
                scenarios.push({ feature: id, arch, runner: RUNNERS[arch] });
            }
        }
    }
    for (const [name, count] of [["feature x image", tests.length], ["scenario", scenarios.length]] as const) {
        if (count > MATRIX_LIMIT) {
            throw new Error(
                `This change selects ${count} ${name} jobs, over GitHub's ${MATRIX_LIMIT}-job matrix limit. ` +
                    "Split the pull request so fewer features are affected at once.",
            );
        }
    }
    return { tests, scenarios, runGlobal: selection.runGlobal, reasons: Object.fromEntries(selection.reasons) };
}
