// Shared model of the feature collection: features, their in-repo dependencies, compatibility
// lists, and test scenarios. The loaders read the working tree; everything else is pure so the
// selection logic can be unit-tested without a repository.
import { join } from "jsr:@std/path@1.1.6";
import { parse as parseJsonc } from "jsr:@std/jsonc@1.0.3";
import Ajv from "npm:ajv@8.20.0";

/** OCI namespace every feature of this repository is published under. */
export const NAMESPACE = "ghcr.io/hoshiori-dev/devcontainer-features";

/** GitHub-hosted runner label for each architecture a compatibility entry may name. */
export const RUNNERS = { amd64: "ubuntu-24.04", arm64: "ubuntu-24.04-arm" } as const;
export type Arch = keyof typeof RUNNERS;

/** Repository paths whose change can break feature testing itself; they select the canary set. */
export const INFRA_PATHS = [
    ".github/workflows/ci.yml",
    ".github/actions/",
    "scripts/lib/",
    "scripts/affected.ts",
    "scripts/test_feature.ts",
    "test/canary.json",
    "test/compatibility.schema.json",
];

/** GitHub's per-workflow-run limit on jobs generated by one matrix. */
export const MATRIX_LIMIT = 256;

export interface CompatEntry {
    image: string;
    arch?: Arch[];
    remoteUser?: string;
}

export interface Compat {
    images: CompatEntry[];
    idempotencyExemption?: string;
}

export interface Scenario {
    name: string;
    image?: string;
    usesBuild: boolean;
    /** Feature keys exactly as written in scenarios.json. */
    featureKeys: string[];
}

export interface FeatureInfo {
    id: string;
    /** Parsed devcontainer-feature.json, or undefined when it could not be read. */
    json?: Record<string, unknown>;
    jsonError?: string;
    /** In-repo feature ids named in dependsOn. */
    dependsOn: string[];
    /** In-repo feature ids named in installsAfter. */
    installsAfter: string[];
    /** In-repo feature ids installed by this feature's test scenarios. */
    scenarioRefs: string[];
    scenarios: Scenario[];
    compat?: Compat;
    compatError?: string;
}

export interface RepoModel {
    features: Map<string, FeatureInfo>;
    /** In-repo feature ids installed by test/_global scenarios. */
    globalRefs: string[];
    hasGlobal: boolean;
    canary: string[];
}

/** Returns the feature id when `ref` points into this repository's OCI namespace. */
export function inRepoId(ref: string): string | undefined {
    const prefix = `${NAMESPACE}/`;
    if (!ref.toLowerCase().startsWith(prefix)) return undefined;
    const match = /^([a-z0-9]+(?:[._-][a-z0-9]+)*)(?:[:@].*)?$/.exec(ref.slice(prefix.length));
    return match?.[1];
}

/** Resolves a scenario feature key: a bare key is a local feature id, a full ref may be in-repo. */
export function scenarioKeyId(key: string, known: Set<string>): string | undefined {
    if (!key.includes("/")) return known.has(key) ? key : undefined;
    return inRepoId(key);
}

function unique<T>(items: Iterable<T>): T[] {
    return [...new Set(items)];
}

function refsOf(value: unknown): string[] {
    if (Array.isArray(value)) return value.filter((v): v is string => typeof v === "string");
    if (value && typeof value === "object") return Object.keys(value);
    return [];
}

/** In-repo feature ids referenced by a dependsOn object or installsAfter array. */
export function inRepoRefs(value: unknown): string[] {
    return unique(refsOf(value).map(inRepoId).filter((id): id is string => id !== undefined));
}

export function parseScenarios(value: unknown): Scenario[] {
    if (!value || typeof value !== "object" || Array.isArray(value)) {
        throw new Error("scenarios.json must be an object mapping scenario names to dev container configs");
    }
    return Object.entries(value as Record<string, unknown>).map(([name, raw]) => {
        const config = (raw ?? {}) as Record<string, unknown>;
        return {
            name,
            image: typeof config.image === "string" ? config.image : undefined,
            usesBuild: config.build !== undefined,
            featureKeys: refsOf(config.features),
        };
    });
}

/** Default architecture list of a compatibility entry. */
export function archesOf(entry: CompatEntry): Arch[] {
    return entry.arch ?? ["amd64"];
}

// ---------------------------------------------------------------------------------------------
// Loaders
// ---------------------------------------------------------------------------------------------

export async function readJsonc(path: string): Promise<unknown> {
    return parseJsonc(await Deno.readTextFile(path));
}

export async function exists(path: string): Promise<boolean> {
    try {
        await Deno.stat(path);
        return true;
    } catch (error) {
        if (error instanceof Deno.errors.NotFound) return false;
        throw error;
    }
}

async function listDirs(path: string): Promise<string[]> {
    if (!(await exists(path))) return [];
    const names: string[] = [];
    for await (const entry of Deno.readDir(path)) if (entry.isDirectory) names.push(entry.name);
    return names.sort();
}

let compatValidator: ((value: unknown) => string | undefined) | undefined;

/** Validates a parsed compatibility.json against test/compatibility.schema.json. */
export async function compatSchemaErrors(root: string, value: unknown): Promise<string | undefined> {
    if (!compatValidator) {
        const schema = await readJsonc(join(root, "test", "compatibility.schema.json")) as Record<string, unknown>;
        // deno-lint-ignore no-explicit-any
        const ajv = new (Ajv as any)({ allErrors: true, strict: false });
        const validate = ajv.compile(schema);
        compatValidator = (candidate) =>
            validate(candidate)
                ? undefined
                : ajv.errorsText(validate.errors, { dataVar: "compatibility.json", separator: "; " });
    }
    return compatValidator(value);
}

export async function loadFeature(root: string, id: string): Promise<FeatureInfo> {
    const info: FeatureInfo = { id, dependsOn: [], installsAfter: [], scenarioRefs: [], scenarios: [] };
    try {
        info.json = await readJsonc(join(root, "src", id, "devcontainer-feature.json")) as Record<string, unknown>;
        info.dependsOn = inRepoRefs(info.json.dependsOn);
        info.installsAfter = inRepoRefs(info.json.installsAfter);
    } catch (error) {
        info.jsonError = error instanceof Error ? error.message : String(error);
    }
    const compatPath = join(root, "test", id, "compatibility.json");
    if (!(await exists(compatPath))) {
        info.compatError = "missing";
    } else {
        try {
            const compat = await readJsonc(compatPath);
            const problem = await compatSchemaErrors(root, compat);
            if (problem) info.compatError = problem;
            else info.compat = compat as Compat;
        } catch (error) {
            info.compatError = error instanceof Error ? error.message : String(error);
        }
    }
    const scenariosPath = join(root, "test", id, "scenarios.json");
    if (await exists(scenariosPath)) info.scenarios = parseScenarios(await readJsonc(scenariosPath));
    return info;
}

/** Loads every feature under src/ plus the global scenarios and the canary list. */
export async function loadRepo(root: string): Promise<RepoModel> {
    const features = new Map<string, FeatureInfo>();
    for (const id of await listDirs(join(root, "src"))) features.set(id, await loadFeature(root, id));
    const known = new Set(features.keys());
    for (const feature of features.values()) {
        feature.scenarioRefs = unique(
            feature.scenarios.flatMap((s) => s.featureKeys)
                .map((key) => scenarioKeyId(key, known))
                .filter((ref): ref is string => ref !== undefined && ref !== feature.id),
        );
    }
    const globalPath = join(root, "test", "_global", "scenarios.json");
    const hasGlobal = await exists(globalPath);
    const globalRefs = hasGlobal
        ? unique(
            parseScenarios(await readJsonc(globalPath)).flatMap((s) => s.featureKeys)
                .map((key) => scenarioKeyId(key, known))
                .filter((ref): ref is string => ref !== undefined),
        )
        : [];
    const canaryPath = join(root, "test", "canary.json");
    const canary = (await exists(canaryPath))
        ? ((await readJsonc(canaryPath)) as { features?: string[] }).features ?? []
        : [];
    return { features, globalRefs, hasGlobal, canary };
}

// ---------------------------------------------------------------------------------------------
// Graph and selection (pure)
// ---------------------------------------------------------------------------------------------

/** Every in-repo feature `feature` needs to install or test: dependsOn, installsAfter, scenarios. */
export function testEdges(feature: FeatureInfo): string[] {
    return unique([...feature.dependsOn, ...feature.installsAfter, ...feature.scenarioRefs])
        .filter((id) => id !== feature.id);
}

/** Transitive in-repo dependsOn closure of `id`, excluding `id` itself, in discovery order. */
export function dependsOnClosure(model: RepoModel, id: string): string[] {
    const seen = new Set<string>();
    const queue = [...(model.features.get(id)?.dependsOn ?? [])];
    while (queue.length > 0) {
        const next = queue.shift()!;
        if (next === id || seen.has(next)) continue;
        seen.add(next);
        queue.push(...(model.features.get(next)?.dependsOn ?? []));
    }
    return [...seen];
}

/** Finds one dependsOn cycle, returned as the ids along it, or undefined when there is none. */
export function findDependsOnCycle(model: RepoModel): string[] | undefined {
    const state = new Map<string, "visiting" | "done">();
    const stack: string[] = [];
    const visit = (id: string): string[] | undefined => {
        if (state.get(id) === "done") return undefined;
        if (state.get(id) === "visiting") return [...stack.slice(stack.indexOf(id)), id];
        state.set(id, "visiting");
        stack.push(id);
        for (const dep of model.features.get(id)?.dependsOn ?? []) {
            if (!model.features.has(dep)) continue;
            const cycle = visit(dep);
            if (cycle) return cycle;
        }
        stack.pop();
        state.set(id, "done");
        return undefined;
    };
    for (const id of model.features.keys()) {
        const cycle = visit(id);
        if (cycle) return cycle;
    }
    return undefined;
}

export type PathKind =
    | { kind: "feature"; id: string }
    | { kind: "global" }
    | { kind: "infra" }
    | { kind: "other" };

export function classifyPath(path: string): PathKind {
    const parts = path.split("/");
    if (parts[0] === "src" && parts.length > 2) return { kind: "feature", id: parts[1] };
    if (parts[0] === "test" && parts.length > 2) {
        if (parts[1] === "_global") return { kind: "global" };
        if (!parts[1].startsWith("_")) return { kind: "feature", id: parts[1] };
    }
    if (INFRA_PATHS.some((p) => (p.endsWith("/") ? path.startsWith(p) : path === p))) return { kind: "infra" };
    return { kind: "other" };
}

export interface Selection {
    /** Affected feature id → why it was selected. */
    reasons: Map<string, string>;
    runGlobal: boolean;
}

/** Selects the features a set of changed paths affects, following dependents transitively. */
export function selectAffected(changed: string[], model: RepoModel): Selection {
    const reasons = new Map<string, string>();
    let globalChanged = false;
    let infraChanged = false;
    for (const path of changed) {
        const kind = classifyPath(path);
        if (kind.kind === "feature" && model.features.has(kind.id) && !reasons.has(kind.id)) {
            reasons.set(kind.id, "changed");
        } else if (kind.kind === "global") globalChanged = true;
        else if (kind.kind === "infra") infraChanged = true;
    }
    const dependents = new Map<string, string[]>();
    for (const feature of model.features.values()) {
        for (const dep of testEdges(feature)) dependents.set(dep, [...(dependents.get(dep) ?? []), feature.id]);
    }
    const queue = [...reasons.keys()];
    while (queue.length > 0) {
        const id = queue.shift()!;
        for (const dependent of dependents.get(id) ?? []) {
            if (reasons.has(dependent)) continue;
            reasons.set(dependent, `depends on ${id}`);
            queue.push(dependent);
        }
    }
    // Canaries exercise the pipeline itself; their dependents are not pulled in, keeping the set bounded.
    if (infraChanged) {
        for (const id of model.canary) if (model.features.has(id) && !reasons.has(id)) reasons.set(id, "canary");
    }
    const runGlobal = model.hasGlobal && (globalChanged || model.globalRefs.some((id) => reasons.has(id)));
    return { reasons, runGlobal };
}

export interface TestJob {
    feature: string;
    image: string;
    arch: Arch;
    runner: string;
    remoteUser: string;
}

export interface Plan {
    tests: TestJob[];
    scenarios: { feature: string }[];
    runGlobal: boolean;
    reasons: Record<string, string>;
}

/** Expands a selection into CI matrices; throws with a fix-it message on unusable input. */
export function buildPlan(selection: Selection, model: RepoModel): Plan {
    const tests: TestJob[] = [];
    const scenarios: { feature: string }[] = [];
    for (const id of [...selection.reasons.keys()].sort()) {
        const feature = model.features.get(id)!;
        if (!feature.compat) {
            throw new Error(
                `test/${id}/compatibility.json is ${feature.compatError === "missing" ? "missing" : "invalid"}` +
                    (feature.compatError && feature.compatError !== "missing" ? ` (${feature.compatError})` : "") +
                    ". CI cannot know which images to test the feature on. Fix the file; see .agents/knowledge/testing.md.",
            );
        }
        for (const entry of feature.compat.images) {
            for (const arch of archesOf(entry)) {
                tests.push({
                    feature: id,
                    image: entry.image,
                    arch,
                    runner: RUNNERS[arch],
                    remoteUser: entry.remoteUser ?? "",
                });
            }
        }
        if (feature.scenarios.length > 0) scenarios.push({ feature: id });
    }
    for (const [name, count] of [["feature x image", tests.length], ["scenario", scenarios.length]] as const) {
        if (count > MATRIX_LIMIT) {
            throw new Error(
                `This change selects ${count} ${name} jobs, over GitHub's ${MATRIX_LIMIT}-job matrix limit. ` +
                    "Split the pull request so fewer features are affected at once.",
            );
        }
    }
    return { tests, scenarios, runGlobal: selection.runGlobal, reasons: Object.fromEntries(selection.reasons) };
}
