#!/usr/bin/env -S deno run --allow-read --allow-write=/tmp --allow-run=devcontainer,docker --allow-net=localhost
// Runs `devcontainer features test` against a staged copy of the repository whose in-repo references
// point at a throwaway local OCI registry holding this checkout's features (scripts/lib/stage.ts).
// CI jobs and `just test` both call this script, so a local run is the same command a CI job ran.
//
//   scripts/test_feature.ts --feature <id> [--image <ref>]... [--remote-user <user>]
//   scripts/test_feature.ts --feature <id> --mode scenarios
//   scripts/test_feature.ts --mode global
//
// Mode `default` runs the autogenerated test and, when test/<id>/duplicate.sh exists, the
// install-twice test, once per image. Without --image it uses every image in
// test/<id>/compatibility.json that lists this machine's architecture. The remote user comes from
// --remote-user, else from the image's compatibility entry, as in CI.
// --preserve keeps test containers; --keep keeps the staging directory and prints its path.
// The registry container and the staging directory are removed on success, failure, and on
// SIGINT, SIGTERM, or SIGHUP, which also stop the running devcontainer command; a test container
// that command had started may remain (`docker ps -a`), as after interrupting the CLI directly.
import { parseArgs } from "jsr:@std/cli@1.0.32/parse-args";
import { type Arch, archesOf, loadFeature, REPO, type RepoModel, scenarioKeyId } from "./lib/repo.ts";
import { stage } from "./lib/stage.ts";

const HOST_ARCH: Arch = Deno.build.arch === "aarch64" ? "arm64" : "amd64";

/** Registry the staged features are published to: registry 3.1.2, multi-arch index digest. */
export const REGISTRY_IMAGE = "registry:3@sha256:ddf754342cfc8acc51a56d5d0ab6af06826461864460636d8bd5c546dab2a7b8";

/** Exit code a shell reports for each signal the script cleans up after (128 + signal number). */
const SIGNALS = { SIGHUP: 129, SIGINT: 130, SIGTERM: 143 } as const;

/** The command run() is waiting on, so a signal handler can stop it before removing what it uses. */
let current: Deno.ChildProcess | undefined;

async function run(command: string, args: string[]): Promise<boolean> {
    console.log(`\n$ ${command} ${args.join(" ")}`);
    current = new Deno.Command(command, { args, stdout: "inherit", stderr: "inherit" }).spawn();
    try {
        return (await current.status).success;
    } finally {
        current = undefined;
    }
}

async function capture(command: string, args: string[]): Promise<string> {
    const output = await new Deno.Command(command, { args, stderr: "inherit" }).output();
    if (!output.success) throw new Error(`${command} ${args.join(" ")} failed`);
    return new TextDecoder().decode(output.stdout).trim();
}

/** Waits until the registry container answers on its loopback port; returns `localhost:<port>`. */
async function registryHost(container: string): Promise<string> {
    const port = (await capture("docker", ["port", container, "5000/tcp"])).split("\n")[0].split(":").pop();
    const host = `localhost:${port}`;
    for (let attempt = 0; attempt < 50; attempt++) {
        try {
            const response = await fetch(`http://${host}/v2/`);
            await response.body?.cancel();
            if (response.ok) return host;
        } catch {
            // not listening yet
        }
        await new Promise((resolve) => setTimeout(resolve, 200));
    }
    throw new Error(`the local registry did not answer on ${host} within 10 s`);
}

/** The features a mode tests; stage() adds their install closure. */
function roots(mode: string, feature: string | undefined): (model: RepoModel) => string[] {
    return (model) => {
        if (mode === "global") return model.globalRefs;
        const scenarios = mode === "scenarios" ? model.features.get(feature!)?.scenarios ?? [] : [];
        const refs = scenarios.flatMap((s) => s.featureKeys).map(scenarioKeyId);
        return [feature!, ...refs.filter((id): id is string => id !== undefined)];
    };
}

if (import.meta.main) {
    const args = parseArgs(Deno.args, {
        string: ["feature", "mode", "remote-user"],
        collect: ["image"],
        boolean: ["preserve", "keep"],
        default: { mode: "default" },
    });
    const images = ((args.image ?? []) as string[]).filter((image) => image !== "");
    const mode = args.mode;
    if (!["default", "scenarios", "global"].includes(mode)) {
        console.error(`error: --mode must be default, scenarios, or global (got ${mode})`);
        Deno.exit(2);
    }
    if (mode !== "global" && !args.feature) {
        console.error("error: --feature <id> is required unless --mode global");
        Deno.exit(2);
    }

    let targets: { image: string; remoteUser?: string }[] = [];
    if (mode === "default") {
        const feature = await loadFeature(".", args.feature!);
        const listed = (image: string) => feature.compat?.images.find((entry) => entry.image === image);
        if (images.length > 0) {
            targets = images.map((image) => ({ image, remoteUser: args["remote-user"] ?? listed(image)?.remoteUser }));
        } else if (feature.compat) {
            targets = feature.compat.images.filter((entry) => archesOf(entry).includes(HOST_ARCH))
                .map((entry) => ({ image: entry.image, remoteUser: args["remote-user"] ?? entry.remoteUser }));
        } else {
            console.error(
                `error: test/${args.feature}/compatibility.json is ${feature.compatError ?? "unusable"}; ` +
                    "pass --image or fix the file (see .agents/knowledge/testing.md).",
            );
            Deno.exit(1);
        }
        if (targets.length === 0) {
            console.error(
                `error: no compatibility image of ${args.feature} lists ${HOST_ARCH}, so nothing would run. ` +
                    "Pass --image <ref> to test one anyway.",
            );
            Deno.exit(1);
        }
    }

    const failures: string[] = [];
    const out = await Deno.makeTempDir({ prefix: "feature-test-" });
    // Named up front, so a signal that arrives while `docker run` is still starting it can remove it too.
    const container = `feature-test-registry-${crypto.randomUUID().slice(0, 8)}`;
    let cleaned: Promise<void> | undefined;
    const cleanup = () =>
        cleaned ??= (async () => {
            await new Deno.Command("docker", { args: ["rm", "-f", container], stdout: "null", stderr: "null" })
                .output();
            if (args.keep) {
                console.log(`\nStaging directory kept: ${out} (its registry refs point at a removed registry)`);
            } else await Deno.remove(out, { recursive: true }).catch(() => {});
        })();
    const handlers = Object.entries(SIGNALS).map(([signal, code]) => {
        const handler = () => {
            console.error(`\n${signal}: stopping, then removing the local registry and the staging directory`);
            try {
                current?.kill("SIGTERM");
            } catch {
                // already exited
            }
            cleanup().finally(() => Deno.exit(code));
        };
        Deno.addSignalListener(signal as Deno.Signal, handler);
        return [signal as Deno.Signal, handler] as const;
    });
    try {
        await capture("docker", ["run", "-d", "--rm", "--name", container, "-p", "127.0.0.1::5000", REGISTRY_IMAGE]);
        const host = await registryHost(container);
        const staged = await stage(".", out, host, roots(mode, args.feature));
        console.log(`\nStaged for ${host}: ${staged.join(", ") || "no feature"}`);
        if (staged.length > 0) {
            const published = await run("devcontainer", [
                "features",
                "publish",
                `${out}/src`,
                "--registry",
                host,
                "--namespace",
                REPO,
            ]);
            if (!published) throw new Error(`publishing the staged features to ${host} failed`);
        }

        const common = [
            "features",
            "test",
            "--project-folder",
            out,
            ...(args.preserve ? ["--preserve-test-containers"] : []),
        ];
        if (mode === "global") {
            if (!(await run("devcontainer", [...common, "--global-scenarios-only"]))) failures.push("global scenarios");
        } else if (mode === "scenarios") {
            const ok = await run("devcontainer", [
                ...common,
                "--features",
                args.feature!,
                "--skip-autogenerated",
                "--skip-duplicated",
            ]);
            if (!ok) failures.push(`${args.feature} scenarios`);
        } else {
            for (const target of targets) {
                const user = target.remoteUser ? ["--remote-user", target.remoteUser] : [];
                const ok = await run("devcontainer", [
                    ...common,
                    "--features",
                    args.feature!,
                    "--base-image",
                    target.image,
                    "--skip-scenarios",
                    ...user,
                ]);
                if (!ok) failures.push(`${args.feature} on ${target.image}`);
            }
        }
    } catch (error) {
        failures.push(`setup (${error instanceof Error ? error.message : error})`);
    } finally {
        await cleanup();
        for (const [signal, handler] of handlers) Deno.removeSignalListener(signal, handler);
    }
    if (failures.length > 0) {
        console.error(`\nFAILED: ${failures.join(", ")}`);
        Deno.exit(1);
    }
}
