#!/usr/bin/env -S deno run --allow-read --allow-write=/tmp --allow-run=devcontainer
// Runs `devcontainer features test` against a staged copy of the repository in which in-repo
// dependencies resolve to this checkout (scripts/lib/stage.ts). CI jobs and `just test` both call
// this script, so a local run is the same command a CI job ran.
//
//   scripts/test_feature.ts --feature <id> [--image <ref>]... [--remote-user <user>]
//   scripts/test_feature.ts --feature <id> --mode scenarios
//   scripts/test_feature.ts --mode global
//
// Mode `default` runs the autogenerated test and, when test/<id>/duplicate.sh exists, the
// install-twice test, once per image. Without --image it uses every image in
// test/<id>/compatibility.json that lists this machine's architecture.
// --preserve keeps test containers; --keep keeps the staging directory and prints its path.
import { parseArgs } from "jsr:@std/cli@1.0.32/parse-args";
import { type Arch, archesOf, loadFeature } from "./lib/repo.ts";
import { stage } from "./lib/stage.ts";

const HOST_ARCH: Arch = Deno.build.arch === "aarch64" ? "arm64" : "amd64";

async function devcontainer(args: string[]): Promise<boolean> {
    console.log(`\n$ devcontainer ${args.join(" ")}`);
    const status = await new Deno.Command("devcontainer", { args, stdout: "inherit", stderr: "inherit" }).spawn()
        .status;
    return status.success;
}

if (import.meta.main) {
    const args = parseArgs(Deno.args, {
        string: ["feature", "mode", "remote-user"],
        collect: ["image"],
        boolean: ["preserve", "keep"],
        default: { mode: "default" },
    });
    const images = ((args.image ?? []) as string[]).filter((image) => image !== "");
    const mode = args.mode;
    if (!["default", "scenarios", "global"].includes(mode)) {
        console.error(`error: --mode must be default, scenarios, or global (got ${mode})`);
        Deno.exit(2);
    }
    if (mode !== "global" && !args.feature) {
        console.error("error: --feature <id> is required unless --mode global");
        Deno.exit(2);
    }

    const out = await Deno.makeTempDir({ prefix: "feature-test-" });
    await stage(".", out);
    const common = [
        "features",
        "test",
        "--project-folder",
        out,
        ...(args.preserve ? ["--preserve-test-containers"] : []),
    ];
    const failures: string[] = [];

    if (mode === "global") {
        if (!(await devcontainer([...common, "--global-scenarios-only"]))) failures.push("global scenarios");
    } else if (mode === "scenarios") {
        const ok = await devcontainer([
            ...common,
            "--features",
            args.feature!,
            "--skip-autogenerated",
            "--skip-duplicated",
        ]);
        if (!ok) failures.push(`${args.feature} scenarios`);
    } else {
        const feature = await loadFeature(".", args.feature!);
        let targets: { image: string; remoteUser?: string }[];
        if (images.length > 0) {
            targets = images.map((image) => ({ image, remoteUser: args["remote-user"] }));
        } else if (feature.compat) {
            targets = feature.compat.images.filter((entry) => archesOf(entry).includes(HOST_ARCH));
        } else {
            console.error(
                `error: test/${args.feature}/compatibility.json is ${feature.compatError ?? "unusable"}; ` +
                    "pass --image or fix the file (see .agents/knowledge/testing.md).",
            );
            Deno.exit(1);
        }
        if (targets.length === 0) console.error(`note: no compatibility image of ${args.feature} lists ${HOST_ARCH}.`);
        for (const target of targets) {
            const user = target.remoteUser ? ["--remote-user", target.remoteUser] : [];
            const ok = await devcontainer([
                ...common,
                "--features",
                args.feature!,
                "--base-image",
                target.image,
                "--skip-scenarios",
                ...user,
            ]);
            if (!ok) failures.push(`${args.feature} on ${target.image}`);
        }
    }

    if (args.keep) console.log(`\nStaging directory kept: ${out}`);
    else await Deno.remove(out, { recursive: true });
    if (failures.length > 0) {
        console.error(`\nFAILED: ${failures.join(", ")}`);
        Deno.exit(1);
    }
}
