#!/usr/bin/env -S deno run --allow-read --allow-write=/tmp --allow-run=devcontainer,docker --allow-net=localhost
// Runs `devcontainer features test` against a staged copy of the repository whose in-repo references
// point at a throwaway local OCI registry holding this checkout's features (scripts/lib/stage.ts).
// CI jobs and `just test` both call this script, so a local run is the same command a CI job ran.
//
//   scripts/test_feature.ts --feature <id> [--image <ref>]... [--remote-user <user>]
//   scripts/test_feature.ts --feature <id> --mode scenarios
//   scripts/test_feature.ts --mode global
//
// Mode `default` runs the autogenerated test and, when test/<id>/duplicate.sh exists, the
// install-twice test, once per image. Without --image it uses every image in
// test/<id>/compatibility.json that lists this machine's architecture.
// --preserve keeps test containers; --keep keeps the staging directory and prints its path.
import { parseArgs } from "jsr:@std/cli@1.0.32/parse-args";
import { type Arch, archesOf, loadFeature, REPO } from "./lib/repo.ts";
import { stage } from "./lib/stage.ts";

const HOST_ARCH: Arch = Deno.build.arch === "aarch64" ? "arm64" : "amd64";

/** Registry the staged features are published to: registry 3.1.2, multi-arch index digest. */
export const REGISTRY_IMAGE = "registry:3@sha256:ddf754342cfc8acc51a56d5d0ab6af06826461864460636d8bd5c546dab2a7b8";

async function run(command: string, args: string[]): Promise<boolean> {
    console.log(`\n$ ${command} ${args.join(" ")}`);
    const status = await new Deno.Command(command, { args, stdout: "inherit", stderr: "inherit" }).spawn().status;
    return status.success;
}

async function capture(command: string, args: string[]): Promise<string> {
    const output = await new Deno.Command(command, { args, stderr: "inherit" }).output();
    if (!output.success) throw new Error(`${command} ${args.join(" ")} failed`);
    return new TextDecoder().decode(output.stdout).trim();
}

/** Starts the registry on a free loopback port; returns its container id and `localhost:<port>`. */
async function startRegistry(): Promise<{ container: string; host: string }> {
    const container = await capture("docker", ["run", "-d", "--rm", "-p", "127.0.0.1::5000", REGISTRY_IMAGE]);
    try {
        const port = (await capture("docker", ["port", container, "5000/tcp"])).split("\n")[0].split(":").pop();
        const host = `localhost:${port}`;
        for (let attempt = 0; attempt < 50; attempt++) {
            try {
                const response = await fetch(`http://${host}/v2/`);
                await response.body?.cancel();
                if (response.ok) return { container, host };
            } catch {
                // not listening yet
            }
            await new Promise((resolve) => setTimeout(resolve, 200));
        }
        throw new Error(`the local registry did not answer on ${host} within 10 s`);
    } catch (error) {
        await capture("docker", ["rm", "-f", container]).catch(() => {});
        throw error;
    }
}

if (import.meta.main) {
    const args = parseArgs(Deno.args, {
        string: ["feature", "mode", "remote-user"],
        collect: ["image"],
        boolean: ["preserve", "keep"],
        default: { mode: "default" },
    });
    const images = ((args.image ?? []) as string[]).filter((image) => image !== "");
    const mode = args.mode;
    if (!["default", "scenarios", "global"].includes(mode)) {
        console.error(`error: --mode must be default, scenarios, or global (got ${mode})`);
        Deno.exit(2);
    }
    if (mode !== "global" && !args.feature) {
        console.error("error: --feature <id> is required unless --mode global");
        Deno.exit(2);
    }

    let targets: { image: string; remoteUser?: string }[] = [];
    if (mode === "default") {
        const feature = await loadFeature(".", args.feature!);
        if (images.length > 0) {
            targets = images.map((image) => ({ image, remoteUser: args["remote-user"] }));
        } else if (feature.compat) {
            targets = feature.compat.images.filter((entry) => archesOf(entry).includes(HOST_ARCH));
        } else {
            console.error(
                `error: test/${args.feature}/compatibility.json is ${feature.compatError ?? "unusable"}; ` +
                    "pass --image or fix the file (see .agents/knowledge/testing.md).",
            );
            Deno.exit(1);
        }
        if (targets.length === 0) {
            console.error(
                `error: no compatibility image of ${args.feature} lists ${HOST_ARCH}, so nothing would run. ` +
                    "Pass --image <ref> to test one anyway.",
            );
            Deno.exit(1);
        }
    }

    const failures: string[] = [];
    const out = await Deno.makeTempDir({ prefix: "feature-test-" });
    let registry: { container: string; host: string } | undefined;
    try {
        registry = await startRegistry();
        await stage(".", out, registry.host);
        const published = await run("devcontainer", [
            "features",
            "publish",
            `${out}/src`,
            "--registry",
            registry.host,
            "--namespace",
            REPO,
        ]);
        if (!published) throw new Error(`publishing the staged features to ${registry.host} failed`);

        const common = [
            "features",
            "test",
            "--project-folder",
            out,
            ...(args.preserve ? ["--preserve-test-containers"] : []),
        ];
        if (mode === "global") {
            if (!(await run("devcontainer", [...common, "--global-scenarios-only"]))) failures.push("global scenarios");
        } else if (mode === "scenarios") {
            const ok = await run("devcontainer", [
                ...common,
                "--features",
                args.feature!,
                "--skip-autogenerated",
                "--skip-duplicated",
            ]);
            if (!ok) failures.push(`${args.feature} scenarios`);
        } else {
            for (const target of targets) {
                const user = target.remoteUser ? ["--remote-user", target.remoteUser] : [];
                const ok = await run("devcontainer", [
                    ...common,
                    "--features",
                    args.feature!,
                    "--base-image",
                    target.image,
                    "--skip-scenarios",
                    ...user,
                ]);
                if (!ok) failures.push(`${args.feature} on ${target.image}`);
            }
        }
    } catch (error) {
        failures.push(`setup (${error instanceof Error ? error.message : error})`);
    } finally {
        if (registry) await capture("docker", ["rm", "-f", registry.container]).catch(() => {});
        if (args.keep) console.log(`\nStaging directory kept: ${out} (its registry refs point at a removed registry)`);
        else await Deno.remove(out, { recursive: true });
    }
    if (failures.length > 0) {
        console.error(`\nFAILED: ${failures.join(", ")}`);
        Deno.exit(1);
    }
}
