#!/usr/bin/env bash
# Autogenerated test: runs as the remote user inside a container built from each compatibility image with openspec
# installed with default options (version latest, disableUpdateCheck true, disableTelemetry false). Covers "Fresh
# container", "Installed locations", "Omitted version", "Verified install", "Omitted disableUpdateCheck", "Caller's
# update-check value wins", and "Omitted disableTelemetry".
set -euo pipefail

# shellcheck source=/dev/null
source dev-container-features-test-lib
# lib.sh is next to this script in the workspace folder, which shellcheck does not see from where it runs.
# shellcheck source=/dev/null
source ./lib.sh

# The version the registry names as latest when the test runs; a release between build and test fails once.
latest="$(
  node -e '
    fetch(process.argv[1], { redirect: "error" })
      .then((response) => response.json())
      .then((document) => console.log(document["dist-tags"].latest));
  ' "${REGISTRY}@fission-ai%2fopenspec"
)"
printf '%s\n' "Expecting OpenSpec ${latest}, as $(id -un)"

# Fresh container: checked before anything here runs openspec.

# Whether nothing below the remote user's home names OpenSpec: no configuration, data, or cache of it.
home_without_openspec() {
  local found
  found="$(find "${HOME}" -iname '*openspec*' -print -quit)" || return
  printf '%s\n' "found: ${found:-nothing}"
  [[ -z "${found}" ]]
}
check "the remote user's home holds no OpenSpec configuration" home_without_openspec

# Whether no npm cache, log, or configuration in the remote user's home names the OpenSpec package: each of the three
# paths is absent or holds no match. The Node.js feature leaves an npm cache of its own there, which is not this
# feature's.
home_without_npm_traces() {
  local location
  local status
  for location in "${HOME}/.npm" "${HOME}/.npmrc" "${HOME}/.cache"; do
    if [[ -e "${location}" ]]; then
      status=0
      grep -rqF fission-ai "${location}" || status=$?
      # grep exits 1 when it read everything and nothing matched; 0 is a match, 2 a file it could not read.
      [[ "${status}" -eq 1 ]] || return 1
    fi
  done
}
check "the remote user's home holds no npm cache or log that the feature created" home_without_npm_traces

# Whether the workspace folder, the directory this test starts in, holds nothing `openspec init` writes: no openspec/
# directory, no agent instruction file, and no hidden entry other than the test's own .devcontainer.
workspace_untouched() {
  local hidden
  hidden="$(find . -mindepth 1 -maxdepth 1 -name '.*' ! -name .devcontainer -print -quit)" || return
  printf '%s\n' "hidden entry found: ${hidden:-none}"
  [[ ! -e openspec && ! -e AGENTS.md && ! -e CLAUDE.md && -z "${hidden}" ]]
}
check "the workspace holds no openspec/ directory or agent skill files" workspace_untouched

# Installed locations.
check "command -v openspec resolves to ${WRAPPER}" test "$(command -v openspec)" = "${WRAPPER}"

# The package and its dependencies are installed as an npm project tree: the two files npm writes for one, and the
# directory that holds the packages.
package_tree_under_prefix() {
  [[ -f "${PREFIX_DIR}/package.json" && -f "${PREFIX_DIR}/package-lock.json" && -d "${PREFIX_DIR}/node_modules" ]]
}
check "the package @fission-ai/openspec and its dependencies are under ${PREFIX_DIR}" package_tree_under_prefix

# Owner, group, and mode are compared with what install.sh gives the wrapper: mode 755 is also what makes openspec
# runnable by every user of the container.
check "${WRAPPER} is owned by root and writable only by root" \
  test "$(stat -c '%U:%G %a' "${WRAPPER}")" = "root:root 755"

# Whether $1 and everything under it belong to the user and the group root and are writable by no one else. The mode
# of a symbolic link is not read: it is 777 for every link.
root_owned() {
  local found
  found="$(find "$1" \( ! -user root -o ! -group root -o \( ! -type l -perm /022 \) \) -print -quit)" || return
  printf '%s\n' "found: ${found:-nothing}"
  [[ -z "${found}" ]]
}
check "everything under ${PREFIX_DIR} is owned by root and writable only by root" root_owned "${PREFIX_DIR}"

# Requirement "Install the requested version".
check "the package and every one of its dependencies were downloaded from ${REGISTRY}" all_from_registry
check "the package installed as @fission-ai/openspec is at exactly the selected version" \
  openspec_package_is_at "${latest}"

# Requirement "Install twice", read as one installation with nothing staged or set aside next to it; the spec has no
# sentence of its own on what an install leaves behind.
check "exactly one OpenSpec installation remains reachable as openspec: nothing is staged or set aside next to it" \
  single_installation

# Omitted version, Verified install.
check "openspec --version, run as the remote user, prints the version the registry names as latest" \
  openspec_reports_version "${latest}"

# Omitted disableUpdateCheck.
check "with OPENSPEC_NO_UPDATE_CHECK unset, the openspec process sees OPENSPEC_NO_UPDATE_CHECK=1" \
  openspec_sees OPENSPEC_NO_UPDATE_CHECK set:1 -u OPENSPEC_NO_UPDATE_CHECK

# Caller's update-check value wins.
check "with OPENSPEC_NO_UPDATE_CHECK set to the empty string, the openspec process sees it set to the empty string" \
  openspec_sees OPENSPEC_NO_UPDATE_CHECK set: OPENSPEC_NO_UPDATE_CHECK=

# Omitted disableTelemetry.
check "the openspec process sees OPENSPEC_TELEMETRY unset when the caller has not set it" \
  openspec_sees OPENSPEC_TELEMETRY unset -u OPENSPEC_TELEMETRY
check "the openspec process sees OPENSPEC_TELEMETRY exactly as the caller's environment has it" \
  openspec_sees OPENSPEC_TELEMETRY set:1 OPENSPEC_TELEMETRY=1

# Fresh container, repeated after the CLI ran: `openspec --version` and the probe wrote nothing either. The spec
# states the scenario for a started container and has no sentence on what running the installed CLI writes.
check "the remote user's home still holds no OpenSpec configuration" home_without_openspec
check "the workspace still holds no openspec/ directory or agent skill files" workspace_untouched

reportResults
