#!/usr/bin/env bash
# Autogenerated test: runs as the remote user inside a container built from each compatibility
# image with openspec installed with default options.
set -e

# shellcheck source=/dev/null
source dev-container-features-test-lib
# shellcheck source=/dev/null
source ./lib.sh

# No file or directory below $1 is owned by anyone but root or writable by group or others.
root_owned() {
  [ -z "$(find "$1" \( ! -user root -o ! -group root -o \( ! -type l -perm /022 \) \) -print -quit)" ]
}

# Fresh container: checked before anything here runs openspec.
check "the home holds no OpenSpec configuration or data" home_without_openspec
check "the home holds no npm cache entry or log of the OpenSpec install" home_without_npm_traces
check "the workspace holds no openspec directory or agent files" workspace_untouched

# The installation: one root-owned prefix, reached through the root-owned wrapper.
check "openspec on PATH is the wrapper" [ "$(command -v openspec)" = "$WRAPPER" ]
check "the wrapper is root's, mode 755" [ "$(stat -c '%U:%G %a' "$WRAPPER")" = "root:root 755" ]
check "the prefix holds package.json" [ -f "$PREFIX_DIR/package.json" ]
check "the prefix holds package-lock.json" [ -f "$PREFIX_DIR/package-lock.json" ]
check "the prefix holds node_modules" [ -d "$PREFIX_DIR/node_modules" ]
check "the prefix is root-owned and writable only by root" root_owned "$PREFIX_DIR"
check "no staging directory or unfinished wrapper is left" single_installation
check "every package came from the public npm registry" all_from_registry

# Omitted version, Verified install.
latest=$(registry_latest)
echo "Expecting OpenSpec $latest, as $(id -un)"
check "openspec --version prints the registry's latest version" [ "$(openspec --version)" = "$latest" ]
check "the installed package is at that version" [ "$(installed_version)" = "$latest" ]

# Omitted disableUpdateCheck, Omitted disableTelemetry, Caller's update-check value wins.
check "with both variables unset, openspec sees the update check off and telemetry untouched" \
  [ "$(seen_env -u OPENSPEC_NO_UPDATE_CHECK -u OPENSPEC_TELEMETRY)" = "NO_UPDATE_CHECK=set:1 TELEMETRY=unset" ]
check "the caller's empty OPENSPEC_NO_UPDATE_CHECK is kept" \
  [ "$(seen_env -u OPENSPEC_TELEMETRY OPENSPEC_NO_UPDATE_CHECK=)" = "NO_UPDATE_CHECK=set: TELEMETRY=unset" ]
check "the caller's OPENSPEC_TELEMETRY is passed through" \
  [ "$(seen_env -u OPENSPEC_NO_UPDATE_CHECK OPENSPEC_TELEMETRY=1)" = "NO_UPDATE_CHECK=set:1 TELEMETRY=set:1" ]

# Fresh container, after openspec ran: --version and the probe write nothing either.
check "the home still holds no OpenSpec configuration or data" home_without_openspec
check "the workspace still holds no openspec directory or agent files" workspace_untouched

reportResults
