#!/usr/bin/env bash
# Autogenerated test: runs inside a container built from each compatibility image with deno
# installed with default options (version latest), as the image's remote user.
set -e

# shellcheck source=/dev/null
source dev-container-features-test-lib

# The version the latest-release pointer names now; a release between build and test fails once.
latest="$(curl --proto '=https' --proto-redir '=https' --fail --silent --show-error --location \
    https://dl.deno.land/release-latest.txt | tr -d '[:space:]')"
latest="${latest#v}"
user="$(id -un)"
if [ "$(id -u)" = 0 ]; then owner=root; else owner="${user}"; fi

check "deno resolves to /usr/local/bin/deno" test "$(command -v deno)" = /usr/local/bin/deno
check "deno reports the latest version ${latest}" bash -c "deno --version | head -n 1 | grep -qx 'deno ${latest} (.*'"
check "deno runs code" bash -c "[ \"\$(deno eval 'console.log(1 + 1)')\" = 2 ]"
check "DENO_NO_UPDATE_CHECK is 1" test "${DENO_NO_UPDATE_CHECK}" = 1
check "DENO_INSTALL_ROOT is /usr/local/share/deno" test "${DENO_INSTALL_ROOT}" = /usr/local/share/deno
tools_dir_after_usr_bin() { case ":${PATH}:" in *:/usr/bin:*:/usr/local/share/deno/bin:*) ;; *) return 1 ;; esac; }
prerequisites_installed() {
    command -v curl && command -v unzip &&
        [ "$(dpkg-query -W -f='${Status}' ca-certificates)" = "install ok installed" ]
}
check "the tools directory is on PATH after /usr/bin" tools_dir_after_usr_bin
check "curl, unzip, and ca-certificates are installed" prerequisites_installed
check "the tools tree is owned by ${owner}" bash -c \
    "[ -d /usr/local/share/deno/bin ] && [ -z \"\$(find /usr/local/share/deno ! -user ${owner})\" ]"

# Spec: a non-root remote user installs a global tool without elevated privileges (root on debian:12).
script="$(mktemp -d)/hello.ts"
echo 'console.log("hello from a global tool");' >"${script}"
check "deno install --global succeeds as ${user}" deno install --global --name deno-feature-hello "${script}"
check "the tool lands in /usr/local/share/deno/bin" test -x /usr/local/share/deno/bin/deno-feature-hello
tool_runs() { [ "$(bash -c deno-feature-hello)" = "hello from a global tool" ]; }
check "the tool runs by name from a new shell" tool_runs

reportResults
