#!/usr/bin/env bash
# Autogenerated test: runs inside a container built from each compatibility image with deno installed with default
# options (version latest), as the image's remote user.
set -euo pipefail

# shellcheck source=/dev/null
source dev-container-features-test-lib

# The version the latest-release pointer names when the test runs; a release between build and test fails once.
latest="$(
  curl --proto '=https' --proto-redir '=https' --fail --silent --show-error --location --retry 3 \
    https://dl.deno.land/release-latest.txt \
    | tr -d '[:space:]'
)"
latest="${latest#v}"

check "deno by name is /usr/local/bin/deno" test "$(readlink -f "$(command -v deno)")" = /usr/local/bin/deno
check "deno --version reports the version the latest-release pointer names (${latest})" bash -c \
  "deno --version | head -n 1 | grep -qx 'deno ${latest} (.*'"
check "deno runs by name as the remote user" bash -c "[[ \"\$(deno eval 'console.log(1 + 1)')\" == 2 ]]"
check "DENO_NO_UPDATE_CHECK is 1" test "${DENO_NO_UPDATE_CHECK:-}" = 1
check "DENO_INSTALL_ROOT is /usr/local/share/deno" test "${DENO_INSTALL_ROOT:-}" = /usr/local/share/deno

# The metadata appends the directory, so it follows every entry of the image's own PATH (the six system directories on
# every compatibility image); a user's shell startup files may append more after it.
tools_dir_after_image_entries() {
  local tools=/usr/local/share/deno/bin
  local path=":${PATH}:"
  local before after entry
  [[ "${path}" == *":${tools}:"* ]] || return 1
  before="${path%%":${tools}:"*}:"
  after=":${path#*":${tools}:"}"
  for entry in /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin; do
    [[ "${before}" == *":${entry}:"* ]] || return 1
    [[ "${after}" != *":${entry}:"* ]] || return 1
  done
}
check "/usr/local/share/deno/bin comes after the image's own PATH entries" tools_dir_after_image_entries

prerequisites_present() {
  local bundle
  command -v curl >/dev/null || return 1
  command -v unzip >/dev/null || return 1
  for bundle in /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/ca-bundle.pem \
    /etc/ssl/cert.pem; do
    if [[ -s "${bundle}" ]]; then return 0; fi
  done
  return 1
}
check "curl, unzip, and a CA certificate bundle are present" prerequisites_present

# The cache helper's globs: an empty directory expands to nothing, hidden files count, and ** descends.
shopt -s nullglob dotglob globstar
package_caches_clean() {
  local entry child
  for entry in /var/lib/apt/lists/*; do
    case "${entry##*/}" in
      lock | partial | auxfiles) ;;
      *) return 1 ;;
    esac
  done
  for entry in /var/cache/apt/archives/*.deb /var/cache/dnf/**/* /var/cache/libdnf5/**/*; do
    if [[ ! -f "${entry}" ]]; then continue; fi
    case "${entry}" in
      # State files that stay in dnf's cache directory after `dnf clean all`; none is repository metadata or a package.
      /var/cache/dnf/packages.db) ;;
      /var/cache/dnf/expired_repos.json) ;;
      /var/cache/dnf/tempfiles.json) ;;
      /var/cache/dnf/.gpgkeyschecked.yum) ;;
      *) return 1 ;;
    esac
  done
  for entry in /var/cache/zypp/*; do
    if [[ -f "${entry}" ]]; then return 1; fi
    if [[ -d "${entry}" ]]; then
      # Bash traversal: openSUSE ships no find.
      for child in "${entry}"/**/*; do
        if [[ -f "${child}" ]]; then return 1; fi
      done
    fi
  done
}
check "the package manager's cache holds no repository metadata or downloaded package" package_caches_clean

# Root owns both directories; a non-root remote user writes them through group deno, root as their owner.
tools_access() {
  local group=root
  local mode=755
  local dir
  if [[ "$(id -u)" != 0 ]]; then
    group=deno
    mode=2775
    [[ " $(id -nG) " == *" deno "* ]] || return 1
  fi
  for dir in /usr/local/share/deno /usr/local/share/deno/bin; do
    [[ "$(stat -c '%U:%G:%a' "${dir}")" == "root:${group}:${mode}" ]] || return 1
    [[ -w "${dir}" ]] || return 1
  done
}
check "the tools directories are owned by root and writable by the remote user" tools_access

# Scenario "Non-root remote user installs a global tool". The remote user is vscode on base:ubuntu24.04 and root on
# every other compatibility image.
script="$(mktemp -d)/hello.ts"
echo 'console.log("hello from a global tool");' >"${script}"
check "deno install --global succeeds as the remote user" \
  deno install --global --name deno-feature-hello "${script}"
check "the executable appears in /usr/local/share/deno/bin" test -x /usr/local/share/deno/bin/deno-feature-hello
tool_runs() {
  [[ "$(bash -c deno-feature-hello)" == "hello from a global tool" ]]
}
check "the tool runs by name from a new shell" tool_runs
login_shell_runs_tool() {
  [[ "$(bash -lc deno-feature-hello)" == "hello from a global tool" ]]
}
check "the tool runs by name in a login shell" login_shell_runs_tool
login_path_holds_tools_dir_once() {
  local login_path
  login_path="$(bash -lc 'printf "%s\n" "${PATH}"')"
  [[ "$(tr ':' '\n' <<<"${login_path}" | grep -cx /usr/local/share/deno/bin)" == 1 ]]
}
check "/usr/local/share/deno/bin appears once in a login shell's PATH" login_path_holds_tools_dir_once

reportResults
