#!/bin/sh
# Autogenerated test: runs as the remote user inside a container built from each compatibility image with uv installed
# with default options. POSIX sh, because alpine:3.24 ships no bash.
set -eu

# shellcheck source=/dev/null
. "$(dirname "$0")/checks.sh"

readonly VOLUME_DIR="/var/lib/uv"
readonly SHARE_DIR="/usr/local/share/uv"
readonly REPAIR="/usr/local/share/uv-feature/repair-volume"
# The feature's five variables as print_uv_env prints them.
readonly EXPECTED_ENV="/var/lib/uv/python|/var/lib/uv/cache|/usr/local/share/uv/tools|/usr/local/share/uv/bin|copy"

is_mount() {
  grep -q "^[^ ]* [^ ]* [^ ]* [^ ]* $1 " /proc/self/mountinfo
}

is_empty_dir() {
  [ -d "$1" ] && [ -z "$(ls -A "$1")" ]
}

no_group_uv() {
  ! grep -q '^uv:' /etc/group
}

member_of_uv() {
  member_of_uv_groups="$(id -Gn)"
  case " ${member_of_uv_groups} " in
    *" uv "*) return 0 ;;
    *) return 1 ;;
  esac
}

# Whether a shell started as `sh $1` (-c, or -lc for a login shell) sees the feature's five variables with their
# values.
shell_has_uv_env() {
  # The variables expand in the shell that sh starts, not in this one.
  # shellcheck disable=SC2016
  shell_has_uv_env_values="$(sh "$1" 'printf "%s|%s|%s|%s|%s" \
    "${UV_PYTHON_INSTALL_DIR}" "${UV_CACHE_DIR}" "${UV_TOOL_DIR}" "${UV_TOOL_BIN_DIR}" "${UV_LINK_MODE}"')"
  [ "${shell_has_uv_env_values}" = "${EXPECTED_ENV}" ]
}

# Whether the PATH value $1 contains the tool directory after every /usr/local/bin and /usr/bin entry.
uv_bin_after_system() {
  uv_bin_after_system_seen=false
  uv_bin_after_system_ifs="${IFS}"
  IFS=:
  for uv_bin_after_system_dir in $1; do
    case "${uv_bin_after_system_dir}" in
      /usr/local/share/uv/bin) uv_bin_after_system_seen=true ;;
      /usr/local/bin | /usr/bin)
        if [ "${uv_bin_after_system_seen}" = true ]; then
          IFS="${uv_bin_after_system_ifs}"
          return 1
        fi
        ;;
    esac
  done
  IFS="${uv_bin_after_system_ifs}"
  [ "${uv_bin_after_system_seen}" = true ]
}

# A writable tool with a system command's name must not shadow that command, in this shell or in a login shell.
system_command_wins() {
  system_command_wins_fixture="${SHARE_DIR}/bin/ls"
  printf '#!/bin/sh\nexit 99\n' >"${system_command_wins_fixture}"
  chmod 0755 "${system_command_wins_fixture}"
  system_command_wins_here="$(command -v ls)"
  system_command_wins_login="$(sh -lc 'command -v ls')"
  rm -f "${system_command_wins_fixture}"
  [ "${system_command_wins_here}" != "${system_command_wins_fixture}" ] \
    && [ "${system_command_wins_login}" != "${system_command_wins_fixture}" ]
}

# New volume: checked before anything runs uv.
check "${VOLUME_DIR} is a mount of the volume" is_mount "${VOLUME_DIR}"
check "the volume holds no files before uv first runs" is_empty_dir "${VOLUME_DIR}"
check "the remote user can create files in the volume" test -w "${VOLUME_DIR}"
check "the volume-repair script is root's, mode 755" [ "$(stat -c '%u %g %a' "${REPAIR}")" = "0 0 755" ]

# Root remote user, Remote user in the group.
if [ "$(id -u)" = 0 ]; then
  check "the install creates no group uv for root" no_group_uv
  for dir in "${VOLUME_DIR}" "${SHARE_DIR}" "${SHARE_DIR}/tools" "${SHARE_DIR}/python" "${SHARE_DIR}/bin"; do
    check "${dir} is owned by root and writable by root only" [ "$(stat -c '%u %g %a' "${dir}")" = "0 0 755" ]
  done
else
  check "the remote user is a member of the group uv" member_of_uv
  for dir in "${VOLUME_DIR}" "${SHARE_DIR}" "${SHARE_DIR}/tools" "${SHARE_DIR}/python" "${SHARE_DIR}/bin"; do
    check "${dir} belongs to the group uv and is writable by its members" \
      [ "$(stat -c '%G %a' "${dir}")" = "uv 2775" ]
  done
fi

# Volume that fits: the new volume fits also when the tooling changed the user's UID. The sudo stub records a call.
stubs="$(mktemp -d)"
cat >"${stubs}/sudo" <<'STUB'
#!/bin/sh
: >"${SUDO_RECORD}"
exit 1
STUB
chmod +x "${stubs}/sudo"
check "the repair succeeds on a new volume" env PATH="${stubs}:${PATH}" SUDO_RECORD="${stubs}/called" "${REPAIR}"
check "sudo is not run on a volume that fits" test ! -e "${stubs}/called"
check "nothing in the volume changes" is_empty_dir "${VOLUME_DIR}"

# Repair skipped for root: an entry another UID owns stays as it is.
if [ "$(id -u)" = 0 ]; then
  touch "${VOLUME_DIR}/foreign"
  chown 23456:23456 "${VOLUME_DIR}/foreign"
  check "the repair succeeds for root" \
    env PATH="${stubs}:${PATH}" SUDO_RECORD="${stubs}/called" "${REPAIR}" 2>"${stubs}/warning"
  check "nothing in the volume changes for root" [ "$(stat -c %u "${VOLUME_DIR}/foreign")" = 23456 ]
  check "no warning is printed for root" test ! -s "${stubs}/warning"
  check "sudo is not run for root" test ! -e "${stubs}/called"
  rm "${VOLUME_DIR}/foreign"
fi
rm -rf "${stubs}"

# Omitted version, glibc image, musl image, Checksum matches.
# The release that `latest` names when the test runs cannot be a literal; a release published between the image build
# and the test fails once.
latest_url="$(curl --proto '=https' --tlsv1.2 -fsS -o /dev/null -w '%{redirect_url}' \
  https://github.com/astral-sh/uv/releases/latest)"
release="${latest_url##*/}"
# The target triple is computed, because the compatibility images cover both architectures and both C libraries.
libc=gnu
for loader in /lib/ld-musl-*.so.1; do
  if [ -e "${loader}" ]; then libc=musl; fi
done
machine="$(uname -m)"
target="${machine}-unknown-linux-${libc}"
printf '%s\n' "Expecting uv ${release} (${target})"
check "uv is installed as /usr/local/bin/uv" [ "$(command -v uv)" = /usr/local/bin/uv ]
check "uvx is installed as /usr/local/bin/uvx" [ "$(command -v uvx)" = /usr/local/bin/uvx ]
check "uv is executable by every user" [ "$(stat -c %a /usr/local/bin/uv)" = 755 ]
check "uvx is executable by every user" [ "$(stat -c %a /usr/local/bin/uvx)" = 755 ]
check "uv --version reports the newest release and the target of this platform" \
  [ "$(uv --version)" = "uv ${release} (${target})" ]
check "uvx --version reports the newest release and the target of this platform" \
  [ "$(uvx --version)" = "uvx ${release} (${target})" ]

# Omitted toolsToInstall.
check "no tool is installed" is_empty_dir "${SHARE_DIR}/tools"
check "no tool executable is installed" is_empty_dir "${SHARE_DIR}/bin"
check "no Python interpreter is downloaded at build time" is_empty_dir "${SHARE_DIR}/python"

# Environment of the remote user, a login shell included.
check "each variable has the stated value" shell_has_uv_env -c
check "PATH contains the tool directory after /usr/local/bin and /usr/bin" uv_bin_after_system "${PATH}"
check "/etc/profile.d/uv.sh is root's, mode 644" [ "$(stat -c '%U %a' /etc/profile.d/uv.sh)" = "root 644" ]
check "each variable has the stated value in a login shell" shell_has_uv_env -lc
# PATH expands in the login shell that sh starts, not in this one.
# shellcheck disable=SC2016
login_path="$(sh -lc 'printf %s "${PATH}"')"
check "a login shell's PATH contains the tool directory after /usr/local/bin and /usr/bin" \
  uv_bin_after_system "${login_path}"
# PATH expands in the login shell that sh starts, not in this one.
# shellcheck disable=SC2016
clean_login_path="$(env -i HOME="${HOME}" sh -lc 'printf %s "${PATH}"')"
check "a login shell from an empty environment has the tool directory after /usr/local/bin and /usr/bin" \
  uv_bin_after_system "${clean_login_path}"
check "system commands take precedence over same-named tools" system_command_wins

# Later feature runs uv: what a later feature relies on during its own install.
check "a later feature finds uv at /usr/local/bin/uv" /usr/local/bin/uv --version
check "UV_PYTHON_INSTALL_DIR is set to /var/lib/uv/python" [ "${UV_PYTHON_INSTALL_DIR}" = /var/lib/uv/python ]

reportResults
