#!/bin/sh
# Autogenerated test: runs as the remote user inside a container built from each compatibility
# image with uv installed with default options.
set -e

# The test library is a bash script. Re-execute with bash, adding it from the image's apk
# repositories on Alpine (inside this test container only).
if [ -z "${FEATURE_TEST_BASH:-}" ]; then
    command -v bash >/dev/null 2>&1 || apk add --no-cache bash >/dev/null
    FEATURE_TEST_BASH=1 exec bash "$0" "$@"
fi

# shellcheck source=/dev/null
. dev-container-features-test-lib

VOLUME=/var/lib/uv

is_mount() {
    grep -q "^[^ ]* [^ ]* [^ ]* [^ ]* $1 " /proc/self/mountinfo
}

is_empty_dir() {
    [ -d "$1" ] && [ -z "$(ls -A "$1")" ]
}

latest_release() {
    location=$(curl --proto '=https' --tlsv1.2 -fsS -o /dev/null -w '%{redirect_url}' \
        https://github.com/astral-sh/uv/releases/latest)
    echo "${location##*/}"
}

# The target triple of the build that fits this container: its architecture and C library.
expected_target() {
    libc=gnu
    for loader in /lib/ld-musl-*.so.1; do
        if [ -e "$loader" ]; then
        libc=musl
    fi
    done
    echo "$(uname -m)-unknown-linux-$libc"
}

# Whether /usr/local/share/uv/bin comes before /usr/local/bin and /usr/bin in the PATH value $1.
uv_bin_first() {
    old_ifs=$IFS
    IFS=:
    for dir in $1; do
        case "$dir" in
            /usr/local/share/uv/bin) IFS=$old_ifs && return 0 ;;
            /usr/local/bin | /usr/bin) IFS=$old_ifs && return 1 ;;
        esac
    done
    IFS=$old_ifs
    return 1
}

# The feature's variables, as one line, in the order of EXPECTED_ENV.
EXPECTED_ENV="/var/lib/uv/python|/var/lib/uv/cache|/usr/local/share/uv/tools|/usr/local/share/uv/bin|copy"
# shellcheck disable=SC2016
PRINT_ENV='printf "%s|%s|%s|%s|%s" "$UV_PYTHON_INSTALL_DIR" "$UV_CACHE_DIR" "$UV_TOOL_DIR" "$UV_TOOL_BIN_DIR" "$UV_LINK_MODE"'

# New volume: checked before anything runs uv.
check "the volume is mounted at $VOLUME" is_mount "$VOLUME"
check "the volume is empty" is_empty_dir "$VOLUME"
check "the volume is owned by the remote user" [ "$(stat -c %U "$VOLUME")" = "$(id -un)" ]

# Omitted version, glibc image, musl image, Checksum matches.
release=$(latest_release)
target=$(expected_target)
echo "Expecting uv $release ($target)"
check "uv is installed as /usr/local/bin/uv" [ "$(command -v uv)" = /usr/local/bin/uv ]
check "uvx is installed as /usr/local/bin/uvx" [ "$(command -v uvx)" = /usr/local/bin/uvx ]
check "uv is executable by every user" [ "$(stat -c %a /usr/local/bin/uv)" = 755 ]
check "uvx is executable by every user" [ "$(stat -c %a /usr/local/bin/uvx)" = 755 ]
check "uv reports the latest release and the build of this platform" [ "$(uv --version)" = "uv $release ($target)" ]
check "uvx reports the latest release and the build of this platform" \
    [ "$(uvx --version)" = "uvx $release ($target)" ]

# Omitted toolsToInstall.
check "no tool is installed" is_empty_dir /usr/local/share/uv/tools
check "no tool executable is installed" is_empty_dir /usr/local/share/uv/bin
check "no interpreter was downloaded at build time" is_empty_dir /usr/local/share/uv/python

# Environment of the remote user, a login shell included.
check "the environment points uv at the feature's locations" [ "$(sh -c "$PRINT_ENV")" = "$EXPECTED_ENV" ]
check "PATH has the tool directory before /usr/local/bin and /usr/bin" uv_bin_first "$PATH"
check "the login-shell snippet is root's, mode 644" [ "$(stat -c '%U %a' /etc/profile.d/uv.sh)" = "root 644" ]
check "a login shell keeps the environment" [ "$(sh -lc "$PRINT_ENV")" = "$EXPECTED_ENV" ]
# shellcheck disable=SC2016
check "a login shell has the tool directory first in PATH" uv_bin_first "$(sh -lc 'printf %s "$PATH"')"
# shellcheck disable=SC2016
check "a login shell from an empty environment has the tool directory first in PATH" \
    uv_bin_first "$(env -i HOME="$HOME" sh -lc 'printf %s "$PATH"')"

# Later feature runs uv: what a later feature relies on during its own install.
check "later features find uv at /usr/local/bin/uv" /usr/local/bin/uv --version
check "later features see UV_PYTHON_INSTALL_DIR" [ "$UV_PYTHON_INSTALL_DIR" = /var/lib/uv/python ]

reportResults
