#!/bin/sh
# Autogenerated test: runs as the remote user inside a container built from each compatibility
# image with uv installed with default options.
set -e

# The test library is a bash script. Re-execute with bash, adding it from the image's apk
# repositories on Alpine (inside this test container only).
if [ -z "${FEATURE_TEST_BASH:-}" ]; then
    command -v bash >/dev/null 2>&1 || apk add --no-cache bash >/dev/null
    FEATURE_TEST_BASH=1 exec bash "$0" "$@"
fi

# shellcheck source=/dev/null
. dev-container-features-test-lib

VOLUME=/var/lib/uv

is_mount() {
    grep -q "^[^ ]* [^ ]* [^ ]* [^ ]* $1 " /proc/self/mountinfo
}

is_empty_dir() {
    [ -d "$1" ] && [ -z "$(ls -A "$1")" ]
}

latest_release() {
    location=$(curl --proto '=https' --tlsv1.2 -fsS -o /dev/null -w '%{redirect_url}' \
        https://github.com/astral-sh/uv/releases/latest)
    echo "${location##*/}"
}

# The target triple of the build that fits this container: its architecture and C library.
expected_target() {
    libc=gnu
    for loader in /lib/ld-musl-*.so.1; do
        if [ -e "$loader" ]; then
        libc=musl
    fi
    done
    echo "$(uname -m)-unknown-linux-$libc"
}

# Whether the tool directory follows existing system directories in the PATH value $1.
uv_bin_after_system() {
    tool_seen=false
    old_ifs=$IFS
    IFS=:
    for dir in $1; do
        case "$dir" in
            /usr/local/share/uv/bin) tool_seen=true ;;
            /usr/local/bin | /usr/bin)
                if [ "$tool_seen" = true ]; then
                    IFS=$old_ifs
                    return 1
                fi
                ;;
        esac
    done
    IFS=$old_ifs
    [ "$tool_seen" = true ]
}

# A writable tool with a system command's name must not shadow that command.
system_command_wins() {
    fixture=/usr/local/share/uv/bin/ls
    printf '#!/bin/sh\nexit 99\n' >"$fixture"
    chmod 0755 "$fixture"
    resolved=$(command -v ls)
    login_resolved=$(sh -lc 'command -v ls')
    rm -f "$fixture"
    [ "$resolved" != "$fixture" ] && [ "$login_resolved" != "$fixture" ]
}

# The feature's variables, as one line, in the order of EXPECTED_ENV.
EXPECTED_ENV="/var/lib/uv/python|/var/lib/uv/cache|/usr/local/share/uv/tools|/usr/local/share/uv/bin|copy"
# shellcheck disable=SC2016
PRINT_ENV='printf "%s|%s|%s|%s|%s" "$UV_PYTHON_INSTALL_DIR" "$UV_CACHE_DIR" "$UV_TOOL_DIR" "$UV_TOOL_BIN_DIR" "$UV_LINK_MODE"'

# New volume: checked before anything runs uv.
check "the volume is mounted at $VOLUME" is_mount "$VOLUME"
check "the volume is empty" is_empty_dir "$VOLUME"
check "the remote user can write the volume" test -w "$VOLUME"
check "the repair script is root-owned and executable" [ "$(stat -c '%u %g %a' /usr/local/share/uv-feature/repair-volume)" = "0 0 755" ]
if [ "$(id -u)" = 0 ]; then
    check "no group uv is created for root" sh -c '! grep -q "^uv:" /etc/group'
    for dir in "$VOLUME" /usr/local/share/uv /usr/local/share/uv/tools /usr/local/share/uv/python /usr/local/share/uv/bin; do
        check "root-only write on $dir" [ "$(stat -c '%u %g %a' "$dir")" = "0 0 755" ]
    done
else
    check "the user is a member of uv" sh -c 'id -Gn | tr " " "\n" | grep -qx uv'
    for dir in "$VOLUME" /usr/local/share/uv /usr/local/share/uv/tools /usr/local/share/uv/python /usr/local/share/uv/bin; do
        check "group uv and setgid write on $dir" [ "$(stat -c '%G %a' "$dir")" = "uv 2775" ]
    done
fi

# The fresh volume fits even when the UID changed; the check must not invoke sudo.
stubs=$(mktemp -d)
cat >"$stubs/sudo" <<'EOF'
#!/bin/sh
: >"$SUDO_RECORD"
exit 1
EOF
chmod +x "$stubs/sudo"
check "a fresh volume fits without sudo" env PATH="$stubs:$PATH" SUDO_RECORD="$stubs/called" /usr/local/share/uv-feature/repair-volume
check "sudo was not called" test ! -e "$stubs/called"
check "the volume stays empty" is_empty_dir "$VOLUME"
if [ "$(id -u)" = 0 ]; then
    touch "$VOLUME/foreign"
    chown 23456:23456 "$VOLUME/foreign"
    check "root skips a foreign entry" env PATH="$stubs:$PATH" SUDO_RECORD="$stubs/called" /usr/local/share/uv-feature/repair-volume 2>"$stubs/warning"
    check "the foreign owner is unchanged" [ "$(stat -c %u "$VOLUME/foreign")" = 23456 ]
    check "root prints no warning" test ! -s "$stubs/warning"
    check "root runs no sudo" test ! -e "$stubs/called"
    rm "$VOLUME/foreign"
fi
rm -rf "$stubs"

# Omitted version, glibc image, musl image, Checksum matches.
release=$(latest_release)
target=$(expected_target)
echo "Expecting uv $release ($target)"
check "uv is installed as /usr/local/bin/uv" [ "$(command -v uv)" = /usr/local/bin/uv ]
check "uvx is installed as /usr/local/bin/uvx" [ "$(command -v uvx)" = /usr/local/bin/uvx ]
check "uv is executable by every user" [ "$(stat -c %a /usr/local/bin/uv)" = 755 ]
check "uvx is executable by every user" [ "$(stat -c %a /usr/local/bin/uvx)" = 755 ]
check "uv reports the latest release and the build of this platform" [ "$(uv --version)" = "uv $release ($target)" ]
check "uvx reports the latest release and the build of this platform" \
    [ "$(uvx --version)" = "uvx $release ($target)" ]

# Omitted toolsToInstall.
check "no tool is installed" is_empty_dir /usr/local/share/uv/tools
check "no tool executable is installed" is_empty_dir /usr/local/share/uv/bin
check "no interpreter was downloaded at build time" is_empty_dir /usr/local/share/uv/python

# Environment of the remote user, a login shell included.
check "the environment points uv at the feature's locations" [ "$(sh -c "$PRINT_ENV")" = "$EXPECTED_ENV" ]
check "PATH has the tool directory after /usr/local/bin and /usr/bin" uv_bin_after_system "$PATH"
check "the login-shell snippet is root's, mode 644" [ "$(stat -c '%U %a' /etc/profile.d/uv.sh)" = "root 644" ]
check "a login shell keeps the environment" [ "$(sh -lc "$PRINT_ENV")" = "$EXPECTED_ENV" ]
# shellcheck disable=SC2016
check "a login shell has the tool directory after system directories in PATH" uv_bin_after_system "$(sh -lc 'printf %s "$PATH"')"
# shellcheck disable=SC2016
check "a login shell from an empty environment has the tool directory after system directories in PATH" \
    uv_bin_after_system "$(env -i HOME="$HOME" sh -lc 'printf %s "$PATH"')"

check "system commands win over same-named tools" system_command_wins

# Later feature runs uv: what a later feature relies on during its own install.
check "later features find uv at /usr/local/bin/uv" /usr/local/bin/uv --version
check "later features see UV_PYTHON_INSTALL_DIR" [ "$UV_PYTHON_INSTALL_DIR" = /var/lib/uv/python ]

reportResults
