#!/usr/bin/env bash
# Autogenerated test: runs as the remote user inside a container built from each compatibility image with
# nvidia-container-toolkit installed with default options (version latest, configureDocker enabled). No compatibility
# image has a Docker daemon, so the Docker configuration is skipped.
set -euo pipefail

# shellcheck source=/dev/null
source dev-container-features-test-lib
# shellcheck source=/dev/null
source "$(dirname "$0")/helpers.sh"

# The package manager lists NVIDIA's stable repository for this architecture as a source.
repository_listed() {
  local url listing
  url="$(toolkit_repo_url)"
  case "$(toolkit_family)" in
    apt)
      as_root apt-get update >/dev/null || return
      listing="$(apt-cache policy)" || return
      ;;
    dnf)
      listing="$(as_root dnf repo info nvidia-container-toolkit)" || return
      # dnf reports the URL it fetches the repository from on its "Base URL" line; only that line is compared.
      listing="$(awk '/Base URL/' <<<"${listing}")"
      ;;
    zypper) listing="$(zypper --non-interactive repos --uri)" || return ;;
  esac
  if [[ "${listing}" != *"${url}"* ]]; then
    printf '%s\n' "the package manager does not list ${url}:" "${listing}" >&2
    return 1
  fi
}

# The newest version-release in NVIDIA's repository when the test runs: `latest` follows the repository, so no literal
# can name it. A release published between the build and the test fails once.
candidate="$(newest_candidate)"

check "nvidia-ctk runs for the remote user" nvidia-ctk --version
check "nvidia-container-cli runs for the remote user" nvidia-container-cli --version
check "all four packages are at the newest version in NVIDIA's repository (${candidate:-none})" \
  packages_at "${candidate}"
check "nvidia-ctk reports the newest version" ctk_reports "${candidate%-*}"
check "the configured repository is NVIDIA's stable repository, signature-checked against a local copy of the key" \
  repository_file_is_expected
check "the package manager lists NVIDIA's stable repository for this architecture" repository_listed
check "NVIDIA's repository is defined once" repository_defined_once
check "the key file holds only NVIDIA's pinned key" key_is_pinned
check "no temporary GNUPGHOME remains" no_temporary_gnupghome
check "no daemon.json is created without a Docker daemon" no_daemon_json

reportResults
