#!/usr/bin/env bash
# Autogenerated test: runs as the remote user inside a container built from each compatibility image with
# nvidia-container-toolkit installed with default options (version latest, configureDocker enabled). No
# compatibility image has a Docker daemon, so the Docker configuration is skipped.
set -e

# shellcheck source=/dev/null
source dev-container-features-test-lib
# shellcheck source=/dev/null
source "$(dirname "$0")/helpers.sh"

CANDIDATE="$(newest_candidate || true)"

check "nvidia-ctk runs for the remote user" nvidia-ctk --version
check "nvidia-container-cli runs for the remote user" nvidia-container-cli --version
check "all four packages are at the newest version in NVIDIA's repository (${CANDIDATE:-none})" \
  packages_at "$CANDIDATE"
check "nvidia-ctk reports the newest version" ctk_reports "${CANDIDATE%-*}"
check "the source definition names NVIDIA's stable repository, signature checks, and the local key" \
  repository_file_is_expected
check "the package manager lists NVIDIA's stable repository for this architecture" repository_listed
check "NVIDIA's repository is defined once" repository_defined_once
check "the key file holds only NVIDIA's pinned key" key_is_pinned
check "no temporary GNUPGHOME remains" no_temporary_gnupghome
check "no daemon.json is created without a Docker daemon" no_daemon_json

reportResults
